/* Página Carreiras */

CREATE TABLE carreiras (
    id_carreira SERIAL PRIMARY KEY,
    nome_carreira VARCHAR(250) NOT NULL,
    img_url TEXT NOT NULL,
    descricao_carreira TEXT NOT NULL
);

INSERT INTO carreiras (nome_carreira, img_url, descricao_carreira) VALUES ('Eletroeletrônica', 'https://bkpsitecpsnew.blob.core.windows.net/uploadsitecps/sites/1/2020/09/Eletroeletronica_Freepik-scaled.jpg', 'Atuação: Eletroeletrônica envolve o estudo de circuitos eletrônicos e sistemas eletroeletrônicos. Os alunos adquirem habilidades em montagem, manutenção e análise de dispositivos, além de aprender sobre microcontroladores e circuitos integrados. Importância do inglês no Mercado: A terminologia técnica em inglês é fundamental para entender circuitos, dispositivos eletrônicos e inovações na área.'),
('Energia Renovável', 'https://s1.static.brasilescola.uol.com.br/be/conteudo/images/830364961522bda6e1569d3958d59ad0.jpg', 'Atuação: Este curso aborda as tecnologias e práticas relacionadas à geração de energia a partir de fontes renováveis, como solar, eólica e biomassa. Os alunos aprendem sobre sistemas de energia, projetos sustentáveis e políticas energéticas. Importância do inglês no Mercado: Muitos estudos e práticas, como energia solar e eólica, têm literatura extensa em inglês, sendo crucial para acompanhar tendências e tecnologias.'),
('Gestão', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3XY65dQtpjXYCwn9O9NIjQkJfKv6SSls2Gg&s', 'Atuação: O curso de Gestão ensina princípios de administração, finanças, marketing e recursos humanos. Os alunos desenvolvem habilidades de liderança e estratégia, preparando-se para gerenciar equipes e projetos em diferentes setores. Importância do inglês no Mercado: O inglês é frequentemente utilizado em teorias de administração, relatórios e apresentações, além de ser a língua predominante em muitos cursos de MBA.'),
('Logística', 'https://site-ingles-theta.vercel.app/img/logistica.webp', 'Atuação: O curso de Logística abrange o planejamento, implementação e controle de fluxos de materiais e informações. Os alunos aprendem sobre transporte, armazenamento, distribuição e gerenciamento da cadeia de suprimentos. Importância do inglês no Mercado: O vocabulário em inglês é chave para entender conceitos de cadeia de suprimentos, gerenciamento de inventário e operações globais.'),
('Metalmecânica', 'https://automatisa.com.br/wp-content/uploads/2023/03/Industria-metal-mecanica-tendencias-que-voce-deve-conhecer.jpg', 'Atuação: Metalmecânica envolve a transformação de metais e a fabricação de peças e componentes. Os alunos estudam processos de usinagem, soldagem e montagem, além de técnicas de controle de qualidade e segurança. Importância do inglês no Mercado: A maioria dos manuais e normas técnicas é redigida em inglês, além de ser importante para a leitura de desenhos técnicos e especificações.'),
('Segurança no Trabalho', 'https://saoc.com.br/wp-content/uploads/2021/12/Qual-a-relacao-entre-saude-e-seguranca-do-trabalho-scaled.jpg', 'Atuação: Este curso trata das práticas e legislações para garantir um ambiente de trabalho seguro. Os alunos aprendem sobre análise de riscos, normativas de segurança, prevenção de acidentes e promoção de saúde ocupacional. Importância do inglês no Mercado: A formação em segurança muitas vezes inclui regulamentações e normas internacionais que estão em inglês, além de termos técnicos específicos.'),
('Tecnologia da Informação', 'https://gestaodesegurancaprivada.com.br/wp-content/uploads/definicao-tecnologia-da-informacao.jpg', 'Atuação: O curso de Tecnologia da Informação foca no uso de tecnologias computacionais para gerenciar dados e sistemas. Os alunos estudam redes, banco de dados, segurança da informação e desenvolvimento de software. Importância do inglês no Mercado: A maior parte da documentação, programação e inovação ocorre em inglês, sendo crucial para a compreensão de linguagens de programação e redes.'),
('Desenvolvimento de Sistemas', 'https://analistademercado.com.br/wp-content/uploads/2022/05/Analise-e-Desenvolvimento-de-Sistemas.png', 'Atuação: O curso de Desenvolvimento de Sistemas capacita os alunos a criar, implementar e gerenciar software e aplicativos. Eles aprendem sobre linguagens de programação, design de interfaces e metodologias ágeis. Importância do inglês no Mercado: A maioria das linguagens de programação e frameworks é baseada em inglês, tornando o conhecimento dessa língua essencial para desenvolvedores.'),
('Mecânica', 'https://cdn.folhape.com.br/img/pc/1100/1/dn_arquivo/2022/07/foto-1_1.jpg', 'Atuação: O curso de Mecânica aborda os princípios da engenharia mecânica, incluindo o design, análise e manutenção de máquinas e sistemas. Os alunos estudam dinâmica, termodinâmica e materiais, preparando-se para atuar em diversas indústrias. Importância do inglês no Mercado: Muitos manuais técnicos, normas e conceitos fundamentais na área são publicados em inglês, o que facilita a integração com tecnologias globais.'),
('Tradução e Interpretação', 'https://site-ingles-theta.vercel.app/img/carreira-de-tradutor1.jpg', 'Atuação: Tradutores e intérpretes convertem textos ou falas de um idioma para outro. Podem trabalhar em diferentes áreas, como tradução técnica, literária ou interpretação simultânea. Mercado: Muitas empresas globais, organizações governamentais e ONGs precisam de tradutores e intérpretes.'),
('Ensino de Inglês', 'https://site-ingles-theta.vercel.app/img/estudo-ingles2.jpg', 'Atuação: Professores de inglês ensinam o idioma a alunos que falam outras línguas, tanto em escolas regulares como em escolas de idiomas. Mercado: Escolas de idiomas, colégios, e plataformas online de ensino oferecem muitas oportunidades.'),
('Marketing Internacional', 'https://site-ingles-theta.vercel.app/img/marketing-internacional4.jpg', 'Atuação: O marketing internacional envolve a criação e implementação de campanhas globais. O inglês é a língua comum para atingir mercados em diferentes partes do mundo. Mercado: Agências de marketing e publicidade, multinacionais e empresas de e-commerce.'),
('Turismo e Hospitalidade', 'https://site-ingles-theta.vercel.app/img/turismo5.webp', 'Atuação: Profissionais da área de turismo trabalham como guias turísticos, agentes de viagem, gestores de hotéis e atendentes em serviços relacionados ao turismo. Mercado: Hotéis, agências de turismo, cruzeiros, e centros turísticos internacionais.'),
('Revisão de Textos em Inglês', 'https://site-ingles-theta.vercel.app/img/textos-ingles8.jpg', 'Atuação: Editores e revisores de texto revisam materiais escritos para garantir precisão e fluência no inglês, especialmente em publicações acadêmicas e empresariais. Mercado: Editoras, empresas de comunicação, empresas de tecnologia e plataformas online.'),
('Roteirista ou Escritor', 'https://site-ingles-theta.vercel.app/img/roteiristas6.jpg', 'Atuação: Escritores e roteiristas que escrevem em inglês podem criar conteúdo para livros, filmes, programas de TV e sites. Mercado: Editoras, estúdios de cinema e televisão, plataformas de streaming.'),
('Consultoria em Comunicação Corporativa Internacional', 'https://site-ingles-theta.vercel.app/img/consultoria-comunica%C3%A7%C3%A3o10.webp', 'Atuação: Especialistas em comunicação internacional ajudam empresas a gerenciar sua imagem global, desenvolver estratégias de comunicação e gerenciar crises internacionais. Mercado: Grandes corporações, consultorias especializadas e ONGs.'),
('Jornalistas e Assessores(as) de Imprensa', 'https://site-ingles-theta.vercel.app/img/jornalismo-internacional6.webp', 'Atuação: Profissionais que cobrem eventos, escrevem reportagens e comunicados de imprensa para empresas ou órgãos de comunicação. A habilidade no inglês é essencial para cobrir notícias internacionais e lidar com empresas globais. Mercado: Agências de comunicação, jornais, revistas, canais de TV e sites de notícias.'),
('Gerentes de Tecnologia da Informação', 'https://site-ingles-theta.vercel.app/img/Gerentes%20-Tecnologia-Informa%C3%A7%C3%A3o%2011.png', 'Atuação: Gerentes de TI coordenam a infraestrutura tecnológica de empresas, supervisionando equipes de suporte, desenvolvimento e segurança de sistemas, com a necessidade de inglês para interagir com fornecedores e equipes internacionais. Mercado: Empresas multinacionais, startups de tecnologia, consultorias de TI e grandes corporações.'),
('Gerente de Projetos Internacionais', 'https://site-ingles-theta.vercel.app/img/gerente-de-projetos.jpg', 'Atuação: Profissionais que coordenam projetos que envolvem equipes e stakeholders de diferentes países, assegurando que prazos e orçamentos sejam cumpridos. Mercado: Multinacionais, empresas de consultoria e organizações sem fins lucrativos.'),
('Programadores(as) e Desenvolvedores(as) Web', 'https://site-ingles-theta.vercel.app/img/desenvolvedor.webp', 'Atuação: Profissionais responsáveis por criar e manter sites, sistemas e aplicativos. O inglês é fundamental, pois a maior parte das linguagens de programação e documentações estão nesse idioma. Mercado: Startups, empresas de tecnologia, agências digitais e multinacionais.'),
('Administradores(as) de Empresas', 'https://site-ingles-theta.vercel.app/img/administrador-empresas.jpeg', 'Atuação: Administradores gerenciam o funcionamento geral de empresas, desde operações até finanças. A fluência em inglês é essencial para trabalhar em corporações internacionais e interagir com parceiros estrangeiros. Mercado: Empresas multinacionais, grandes corporações e consultorias de negócios.'),
('Engenheiro(a) de Software', 'https://site-ingles-theta.vercel.app/img/eng-software.webp', 'Atuação: Engenheiros de software projetam, desenvolvem e mantêm sistemas e aplicativos, muitas vezes usando o inglês para leitura de manuais, participar de conferências e colaborar com equipes globais. Mercado: Empresas de tecnologia, startups, multinacionais e indústrias.'),
('Comissários(as) de Bordo', 'https://site-ingles-theta.vercel.app/img/commisario.jpg', 'Atuação: Comissários de bordo atendem passageiros durante voos, oferecendo serviços e garantindo a segurança. O inglês é necessário para comunicar-se com passageiros internacionais e equipes globais. Mercado: Companhias aéreas internacionais, voos comerciais e privados.'),
('Pilotos(as) de Avião', 'https://site-ingles-theta.vercel.app/img/piloto.jpg', 'Atuação: Pilotos de avião operam aeronaves comerciais e privadas. O inglês é o idioma padrão para a comunicação entre pilotos e torres de controle no mundo todo. Mercado: Companhias aéreas comerciais, aviação privada, transporte de carga.'),
('Tripulantes m Cruzeiro', 'https://site-ingles-theta.vercel.app/img/tripulantes.jpg', 'Atuação: Tripulantes em cruzeiros garantem o bem-estar e entretenimento dos passageiros, além de desempenhar funções operacionais. O inglês é necessário para lidar com passageiros e equipes internacionais. Mercado: Empresas de cruzeiros internacionais, navios de turismo.'),
('Secretariado', 'https://site-ingles-theta.vercel.app/img/secretariado.webp', 'Atuação: Secretários(as) assistem executivos em suas tarefas diárias, organizam agendas e eventos, frequentemente utilizando o inglês para lidar com documentos e correspondências internacionais. Mercado: Empresas multinacionais, consultorias, organizações globais.'),
('Analista de Redes', 'https://site-ingles-theta.vercel.app/img/analistas-de-redes.webp', 'Atuação: Analistas de redes gerenciam e garantem o bom funcionamento de redes de computadores. O inglês é necessário para configurar sistemas globais e trabalhar com documentações técnicas. Mercado: Empresas de tecnologia, provedores de internet, grandes corporações.'),
('Contador(a)', 'https://site-ingles-theta.vercel.app/img/contador.jpg', 'Atuação: Contadores cuidam das finanças de empresas, incluindo declarações de impostos e relatórios financeiros. Para empresas internacionais, o inglês é importante para lidar com normas globais. Mercado: Escritórios de contabilidade, multinacionais, empresas de auditoria.'),
('Representante Comercial', 'https://site-ingles-theta.vercel.app/img/representante-comercial.jpg', 'Atuação: Representantes comerciais vendem produtos ou serviços para outras empresas ou consumidores, frequentemente em mercados internacionais, onde o inglês é necessário para comunicação. Mercado: Empresas de comércio, indústria, empresas de tecnologia e serviços.'),
('Agente de Câmbio', 'https://site-ingles-theta.vercel.app/img/agente-de-cambio.jpg', 'Atuação: Profissionais que realizam a compra e venda de moedas estrangeiras, auxiliando clientes na conversão de moeda e fornecendo informações sobre taxas de câmbio e regulamentações financeiras, além de oferecer consultoria em transações internacionais. Mercado: Bancos, casas de câmbio, instituições financeiras e empresas de turismo.'),
('Advogado(a) Especializado em Direito Internacional', 'https://site-ingles-theta.vercel.app/img/advogado.jpg', 'Atuação: Advogados que lidam com questões de direito internacional representam clientes em disputas legais entre países ou empresas globais, utilizando o inglês para atuar em diferentes jurisdições. Mercado: Escritórios de advocacia internacionais, empresas multinacionais, ONGs.'),
('Especialista em Recursos Humanos em Multinacionais', 'https://site-ingles-theta.vercel.app/img/Especialista-Recursos-Humanos.jpg', 'Atuação: Especialistas em RH gerenciam o recrutamento e desenvolvimento de funcionários, frequentemente usando o inglês para lidar com candidatos e equipes internacionais. Mercado: Grandes empresas, consultorias de RH, corporações multinacionais.'),
('Analista de Business Intelligence (BI)', 'https://site-ingles-theta.vercel.app/img/BI.webp', 'Atuação: Profissionais de BI analisam dados e geram relatórios que ajudam as empresas a tomar decisões estratégicas, com o inglês sendo útil para entender ferramentas e relatórios globais. Mercado: Empresas de tecnologia, consultorias, corporações multinacionais.'),
('Relações Públicas', 'https://site-ingles-theta.vercel.app/img/relacoes-publicas.jpg', 'Atuação: Profissionais que gerenciam a imagem de uma empresa, organização ou pessoa, interagindo com a mídia e com diferentes públicos. O inglês é fundamental para trabalhar com a imprensa e públicos internacionais. Mercado: Agências de comunicação, empresas multinacionais, órgãos públicos.'),
('Relações Internacionais', 'https://site-ingles-theta.vercel.app/img/relacoes-internacionais3.jpg', 'Atuação: Profissionais de relações internacionais atuam na diplomacia, comércio exterior, ONGs e organismos internacionais, promovendo a cooperação entre países e facilitando negociações globais. Eles colaboram com empresas multinacionais e instituições para fortalecer parcerias e promover a integração econômica e política internacional. Mercado: Governos, embaixadas, consulados, empresas multinacionais e instituições internacionais.'),
('Negócios Internacionais', 'https://site-ingles-theta.vercel.app/img/negocios-internacionais7.webp', 'Atuação: Profissionais de negócios internacionais se especializam em comércio exterior, finanças globais e gestão de operações em um ambiente global. Eles são responsáveis por estabelecer e manter relações comerciais com parceiros internacionais, frequentemente utilizando o inglês como língua de comunicação. Mercado: Oportunidades estão disponíveis em multinacionais, bancos, empresas de comércio exterior e instituições financeiras.');

/* Página Dicas */

CREATE TABLE dicas (
    id_dica SERIAL PRIMARY KEY,
    categoria_dica VARCHAR(100) NOT NULL,
    numero_dica INT,
    titulo_dica VARCHAR(250) NOT NULL,
    descricao_dica TEXT,
    img_url TEXT,
    link_img_url TEXT,
    link_url TEXT
);

INSERT INTO dicas (categoria_dica, numero_dica, titulo_dica, descricao_dica, img_url, link_img_url, link_url) VALUES 
('Dicas de Incentivo', 1, 'Queira aprender', 'A lingua inglesa e o idioma mais demandado no mundo. Quando se tem a nocao de que com ela e possivel ir longe e ter varias oportunidades, e mais facil motivar-se para estudar. Voce nao precisa ser o melhor - sabendo pronunciar as palavras e se comunicar com os outros ou com individuos nativos, ja e suficiente. O dominio do ingles permite a interacao e a conexao com pessoas de diversas partes do globo, incentivando a criacao de novas amizades e a compreensao de outras culturas. Ao aprender sobre diferentes pessoas e culturas, voce pode desenvolver uma perspectiva mais ampla sobre o mundo ao seu redor. Ademais, dominar o ingles e uma grande vantagem para o crescimento profissional, uma vez que pode facilitar a obtencao de novas posicoes, melhores salarios e, ate mesmo, uma oportunidade de trabalho no exterior ou em uma empresa multinacional. Isso nao quer dizer que o processo sera simples, porem, trara resultados. Basta voce querer!', 'https://site-ingles-theta.vercel.app/img/dica-img-postit.png', NULL, NULL),
('Dicas de Incentivo', 2, 'Comece o quanto antes', 'Procure organizar uma rotina de estudos o mais antecipado possivel. Nada de procrastinar! A partir disso, voce podera se garantir em provas ou vestibulares, ja que a maioria das vezes, o estudo e o que leva a experiencia. Alem disso, e importante lembrar que o ingles e uma lingua que requer pratica e repeticao para se tornar habilidoso. Portanto, nao se deixe demorar para aprender, mas sim, se concentrar e praticar regularmente.', 'https://site-ingles-theta.vercel.app/img/dica-img-relogio.png', NULL, NULL),
('Dicas de Incentivo', 3, 'Defina objetivos', 'E importante definir objetivos claros, realistas e mensuraveis para o estudo do ingles, pois isso lhe ajudara a manter o foco e a motivacao durante o processo de aprendizado. Tais metas podem ser: Melhoria da pronunciacao: Focar na clareza e precisao da fala. Ampliar o vocabulario: Aprender um certo numero de palavras novas semanalmente. Aprimoramento da compreensao auditiva: Assistir a filmes ou ouvir podcasts em ingles e entender pelo menos 70% do conteudo. Escrita fluida: Praticar redacoes, escrever um diario, textos ou bate-papos em ingles regularmente. Fluencia em Conversacao: Participar de conversas ou grupos de estudo e comunicar-se de forma mais natural.', 'https://site-ingles-theta.vercel.app/img/dica-img-metas.png', NULL, NULL),
('Dicas de Incentivo', 4, 'Faca um curso de ingles', 'Um curso de ingles e essencial pois oferece uma estrutura solida e orientacao para aprender o idioma. Com professores capacitados, voce obtem feedback imediato e personalizado, acelerando seu progresso. Alem disso, os cursos geralmente dispoem de materiais didaticos atualizados e atividades variadas que abrangem as habilidades de leitura, escrita, escuta e fala. Frequentar um ambiente de aprendizado formal tambem incentiva a disciplina e a constancia, indispensaveis para alcancar a fluencia. E, claro, a interacao com outros alunos proporciona pratica em situacoes reais, aumentando sua confianca. Alguns cursos de lingua inglesa de qualidade sao:', NULL, '["https://site-ingles-theta.vercel.app/img/dica-img-cambly.jpg", "https://site-ingles-theta.vercel.app/img/dica-img-fluencypass.png", "https://site-ingles-theta.vercel.app/img/dica-img-cna.png", "https://site-ingles-theta.vercel.app/img/dica-img-fisk.png"]', '["https://www.cambly.com/english?lang=pt", "https://fluencypass.com/", "https://www.cna.com.br/", "https://fisk.com.br/"]'),
('Dicas de Incentivo', 5, 'Coloque o ingles na rotina', 'O principal passo para integrar o ingles em sua rotina e a sua pratica diaria. Como voce pode realizar isso? Recomenda-se assistir a filmes, series e videos na lingua inglesa, alem de alterar o idioma do seu celular para o ingles. E igualmente importante praticar a conversacao com outras pessoas que se encontram em um nivel semelhante ao seu, promovendo assim um treinamento conjunto. Alternativamente, voce pode procurar individuos com proficiencia avancada na lingua, que possam auxilia-lo na correcao de eventuais erros.', 'https://site-ingles-theta.vercel.app/img/homem%20lendo%20livro.jpeg', NULL, NULL),
('Dicas de Incentivo', 6, 'Entenda as suas dificuldades', 'Para avancar no aprendizado de uma nova lingua, e imprescindivel realizar uma autoavaliacao que identifique os pontos em que voce encontra mais dificuldades. A partir dessa analise, recomenda-se registrar palavras e estruturas que apresentam maior desafio e concentrar-se em aprender esses termos. E fundamental praticar constantemente a comunicacao, a leitura e a escrita.', 'https://site-ingles-theta.vercel.app/img/quebra%20cabeca.jpeg', NULL, NULL),
('Dicas de Incentivo', 7, 'Nao se compare', 'Cada individuo possui sua propria maneira de aprender e evoluir; portanto, e aconselhavel nao se comparar com o progresso dos outros. Concentre-se em suas metas e objetivos pessoais, valorizando seu progresso a cada etapa dessa jornada. Por fim, seja gentil consigo mesmo, reconhecendo que nem todos possuem o mesmo ritmo de aprendizado.', NULL, NULL, NULL),
('Dicas de Incentivo', 8, 'Nao tenha medo de errar', 'O ultimo passo consiste em aplicar todas as dicas mencionadas anteriormente, alem de nao ter medo de cometer erros. O processo de aprendizagem de uma nova lingua e desafiador e pode ser demorado; portanto, e de suma importancia praticar intensamente, sem sentir vergonha de seus erros, mas, ao contrario, buscar corrigi-los da melhor maneira possivel.', NULL, NULL, NULL),
('Dicas de Conteudo', NULL, 'Quais conteudos de ingles mais caem no ENEM?', NULL, 'https://site-ingles-theta.vercel.app/img/dica-img-grafico.png', NULL, 'https://oglobo.globo.com/brasil/educacao/enem-e-vestibular/guia/enem-o-que-mais-cai-em-ingles-e-espanhol-saiba-o-que-estudar.ghtml'),
('Dicas de Conteudo', 1, 'Interpretacao de texto', 'E fundamental realizar uma leitura inicial atenta e identificar o tema principal do texto. Observe o vocabulario, atribuindo significado com base no contexto. Em seguida, leia as questoes e, se necessario, releia o texto. Recomenda-se, ainda, praticar a leitura de diferentes tipos de textos em casa, para na hora da prova estar confiante que voce sabe o que fazer.', 'https://site-ingles-theta.vercel.app/img/livro%20e%20oculos.jpeg', NULL, NULL),
('Dicas de Conteudo', 2, 'Vocabulario e gramatica', 'Para um bom ingles, e necessario que voce conheca uma variedade de palavras para poder se comunicar sem dificuldades e repeticoes. Um vocabulario amplo e a chave para uma boa compreensao auditiva e uma escrita avancada. Alem disso, e importante praticar a gramatica para que voce possa compreender melhor o significado das palavras e expressoes. Aqui estao algumas dicas para estes topicos: VOCABULARIO - ESCUTE MUSICAS EM INGLES: Musicas tem a vantagem de usar linguagem informal cotidiana, expressoes idiomaticas e diferentes sotaques, ou seja, sao ferramentas de aprendizado fortissimas que auxiliam no enriquecimento do seu vocabulario. E uma maneira leve de praticar a pronunciacao e a escrita, alem de entender o contexto das palavras. LEIA DIARIAMENTE: Escolha artigos, noticias, blogs e/ou livros que te interessem e sempre que encontrar uma palavra nova, anote-a junto com seu significado. Dessa forma, voce pode similar novas palavras utilizadas na leitura e usa-las no futuro. FILMES E SERIES: Assistir filmes e series em ingles e uma pratica muito eficaz para aprender novas expressoes utilizadas em narrativas. Com ela, voce consegue se familiarizar com o idioma estrangeiro e adaptar os seus ouvidos. CONVERSE EM INGLES: Procure praticar o dialogo em ingles para acostumar-se as pronunciacoes, expressoes e palavras novas. Essa pratica pode ser feita com amigos, familiares ou ate mesmo com estrangeiros. GRAMATICA - "PARTS OF SPEECH": As partes da fala sao a base da lingua inglesa. Aprenda os principais verbos e adjetivos, e compreenda como eles se relacionam com outras classes gramaticais, como os pronomes, os adverbios e os preposicoes. ATENTE-SE AOS HOMOFONOS: Os homofonos sao palavras que se assemelham com outras palavras pela pronunciacao, mas que sao escritas de forma diferente. Na lingua inglesa, ha muitos homofonos que, na hora de uma conversacao ou escrita, podem confundir. Alguns deles sao: "Theyre", "Their" e "There"; "Youre" e "Your"; "For" e "Four"; "Too", "Two" e "To". NAO UTILIZE O "THAT" PARA SE REFERIR A PESSOAS: O "That" e uma palavra utilizada para indicar ao que esta sendo referido na narrativa. Porem, em ingles, nao se deve usa-lo para se referir a pessoas, mas sim para algo ou algos. ESTUDE OS TEMPOS VERBAIS: Compreenda os tempos verbais, principalmente o "Past Simple" e o "Present Perfect" para saber formular frases coerentes com o tempo e o contexto.', NULL, NULL, NULL),
('Dicas de Conteudo', 3, 'Figuras de linguagem', 'As figuras de linguagem sao recursos utilizados na lingua inglesa para tornar a comunicacao mais expressiva e impactante. Elas consistem em expressoes e construcoes que vao alem do sentido literal das palavras, adicionando um toque de criatividade e originalidade ao discurso. Nessa pagina, iremos explorar algumas das figuras de linguagem mais comuns em ingles, suas definicoes e exemplos de uso. FIGURAS DE LINGUAGEM
METAFORA: A metafora e uma figura de linguagem que consiste em atribuir a uma palavra ou expressao um significado diferente do seu sentido literal. Ela cria uma comparacao implicita entre dois elementos, destacando caracteristicas em comum entre eles. Por exemplo: “She is a shining star.” (Ela e uma estrela brilhante.) Neste exemplo, a pessoa esta sendo comparada a uma estrela brilhante, ressaltando sua beleza e brilho.
SIMILE: O simile e uma figura de linguagem semelhante a metafora, porem utiliza a palavra “like” ou “as” para estabelecer a comparacao explicita entre dois elementos. Por exemplo: “He runs like a cheetah.” (Ele corre como um guepardo.) Neste caso, a pessoa esta sendo comparada a um guepardo, enfatizando sua velocidade e agilidade.
PERSONIFICACAO: A personificacao e uma figura de linguagem que atribui caracteristicas humanas a objetos inanimados ou seres nao humanos. Ela torna o discurso mais vivido e interessante. Por exemplo: “The flowers danced in the wind.” (As flores dancavam ao vento.) Aqui, as flores sao personificadas, como se tivessem a capacidade de dancar.
HIPERBOLE: A hiperbole e uma figura de linguagem que consiste em exagerar uma ideia ou uma situacao, enfatizando seu impacto ou importancia. Ela e comumente utilizada para criar um efeito comico ou dramatico. Por exemplo: “Ive told you a million times!” (Eu ja te disse um milhao de vezes!) Neste caso, a pessoa esta exagerando o numero de vezes que repetiu algo, para enfatizar sua frustracao.
IRONIA: A ironia e uma figura de linguagem que consiste em expressar o oposto do que se quer dizer, de forma sarcastica ou humoristica. Ela cria um efeito de contraste entre o que e dito e o que e realmente pretendido. Por exemplo: “What a lovely weather were having today.” (Que clima adoravel estamos tendo hoje.) Neste caso, a pessoa esta sendo ironica, pois o clima esta ruim, mas ela expressa o contrario.
METONIMIA: A metonimia e uma figura de linguagem que consiste em utilizar uma palavra ou expressao para representar outra, com base em uma relacao de proximidade ou associacao. Por exemplo: “The pen is mightier than the sword.” (A caneta e mais poderosa que a espada.) Aqui, a palavra “pen” (caneta) e utilizada para representar a escrita, enquanto a palavra “sword” (espada) representa a violencia.
SINESTESIA: A sinestesia e uma figura de linguagem que consiste em mesclar sensacoes de diferentes sentidos, criando uma experiencia sensorial unica. Por exemplo: “The sweet sound of her voice.” (O som doce de sua voz.) Neste exemplo, a sensacao de docura e atribuida ao som da voz, criando uma imagem sensorial.
EUFEMISMO: O eufemismo e uma figura de linguagem que consiste em suavizar uma expressao ou ideia desagradavel, substituindo-a por outra mais amena. Ele e comumente utilizado para tratar de assuntos delicados ou tabus. Por exemplo: “He passed away.” (Ele faleceu.) Aqui, a expressao “passed away” e utilizada como um eufemismo para “morreu”.
ONOMATOPEIA: A onomatopeia e uma figura de linguagem que consiste em utilizar palavras que imitam sons reais, tornando o discurso mais expressivo e vivido. Por exemplo: “The dog barked loudly.” (O cachorro latiu alto.) A palavra “barked” imita o som do latido do cachorro.
ANTITESE: A antitese e uma figura de linguagem que consiste em estabelecer uma oposicao entre duas ideias ou conceitos, criando um contraste marcante. Por exemplo: “It was the best of times, it was the worst of times.” (Foi o melhor dos tempos, foi o pior dos tempos.) Aqui, a antitese e utilizada para enfatizar a diferenca entre os melhores e piores momentos.
PARADOXO: O paradoxo e uma figura de linguagem que consiste em utilizar uma afirmacao aparentemente contraditoria, mas que possui um sentido logico e profundo. Por exemplo: “Less is more.” (Menos e mais.) Neste caso, a expressao paradoxal enfatiza a ideia de que, em algumas situacoes, menos e realmente mais eficiente.
PLEONASMO: O pleonasmo e uma figura de linguagem que consiste em repetir uma ideia ou informacao de forma redundante, enfatizando-a. Ele e comumente utilizado para criar um efeito de enfase ou reforco. Por exemplo: “I saw it with my own eyes.” (Eu vi com meus proprios olhos.) A expressao “with my own eyes” e um pleonasmo, pois a informacao ja esta implicita no verbo “saw”.
ASSONANCIA: A assonancia e uma figura de linguagem que consiste em repetir sons vocalicos em palavras proximas, criando um efeito sonoro agradavel e harmonioso. Por exemplo: “The rain in Spain stays mainly in the plain.” (A chuva na Espanha fica principalmente na planicie.) Neste exemplo, a repeticao do som “ai” nas palavras “rain”, “Spain” e “mainly” cria um efeito de assonancia.', NULL, NULL, NULL);