CREATE DATABASE portal_ingles;

CREATE TYPE nivel_enum AS ENUM ('Basico', 'Intermediario', 'Avancado', 'Proeficiente');

CREATE TABLE simulados (
    id SERIAL PRIMARY KEY, 
    nivel nivel_enum NOT NULL,
    numero_pergunta INT NOT NULL CHECK (numero_pergunta BETWEEN 1 AND 15), 
    titulo VARCHAR(50) NOT NULL, 
    texto_pergunta TEXT,
    pergunta_texto TEXT NOT NULL, 
    url VARCHAR(255), 
    UNIQUE (nivel, numero_pergunta)
);
CREATE TABLE alternativas (
    id SERIAL PRIMARY KEY, 
    id_pergunta INT NOT NULL, 
    nivel nivel_enum NOT NULL,
    texto_alternativa TEXT NOT NULL, 
    correta BOOLEAN NOT NULL, 
    FOREIGN KEY (id_pergunta) REFERENCES simulados(id) ON DELETE CASCADE
);

-- Nível Básico

INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Basico', 1, '(Enem 2021)', NULL, 'A presença de at odds with na fala da personagem do cartum revela o(a):', 'https://blogger.googleusercontent.com/img/a/AVvXsEhCvRSIDqYEwlUR-cW3xR4EpXkw35jJeGURtAx8e4uvrtKEkBvhGIM13Be357bLKauia5nZqyvEoG6-nkT9W8dIbSmF6UIq_zG2SDzKclfJhtK3WilvF0QDtksY6qDgMH7Z-eTibyCaY5oRWwpL7tFwsE8miV0qhofs9rMicZkzCusC_1_Ym0zlEjoL=s600'),
('Basico', 2, '(Enem 2019)', 'A pet is certainly a great friend. After a difficult day, pet owners quite literally feel the love. In fact, for nearly 25 years, research has shown that living with pets provides certain health benefits. Pets help lower blood pressure and lessen anxiety. They boost our immunity. They can even help you get dates. Allergy Fighters A growing number of studies have suggested that kids growing up in a home with furred animals will have less risk of allergies and asthma. Date Magnets Dogs are great for making love connections. Forget Internet matchmaking – a dog is a natural conversation starter. Dogs for the Aged Walking a dog or just caring for a pet – for elderly people who are able – can provide exercise and companionship. Good for Mind and Soul Like any enjoyable activity, playing with a dog can elevate levels of serotonin and dopamine – nerve transmitters that are known to have pleasurable and calming properties. Good for the Heart Heart attack patients who have pets survive longer than those without, according to several studies.', 'Ao discutir sobre a influência de animais de estimação no bem-estar do ser humano, a autora, a fim de fortalecer seus argumentos, utiliza palavras e expressões como research, a growing number of research e several studies com o objetivo de:', NULL),
('Basico', 3, '(Enem 2016)', 'BOGOF is used as a noun as in There are some great bogofs on at the supermarket or an adjective, usually with a word such as offer or deal — there are some great bogof offers in store. When you combine the first letters of the words in a phrase or the name of an organisation, you have an acronym. Acronyms are spoken as a word so NATO (North Atlantic Treaty Organisation) is not pronounced N-A-T-O. We say NATO. Bogof, when said out loud, is quite comical for a native speaker, as it sounds like an insult, Bog off! meaning go away, leave me alone, slightly childish and a little old-fashioned. BOGOF is the best-known of the supermarket marketing strategies. The concept was first imported from the USA during the 1970s recession, when food prices were very high. It came back into fashion in the late 1990s, led by big supermarket chains trying to gain a competitive advantage over each other. Consumers were attracted by the idea that they could get something for nothing. Who could possibly say no?', 'Considerando-se as informações do texto, a expressão bogof é usada para:', NULL),
('Basico', 4, '(Enem 2022)', NULL, 'Na tirinha, o comportamento da mulher expressa:', 'https://kuadro-static.storage.googleapis.com/050548bae767435282242b1c404c6348/0000.png'),
('Basico', 5, '(Enem 2023)', 'No man is an island, Entire of itself; Every man is a piece of the continent, A part of the main. [...] Any man s death diminishes me, Because I am involved in mankind.', 'Nesse poema, a expressão No man is an island ressalta o(a):', NULL),
('Basico', 6, '(Enem 2022)', 'As my official bio reads, I was made in Cuba, assembled in Spain, and imported to the United States – meaning my mother, seven months pregnant, and the rest of my family arrived as exiles from Cuba to Madrid, where I was born. Less than two months later, we emigrated once more and settled in New York City, then eventually in Miami, where I was raised and educated. Although technically we lived in the United States, the Cuban community was culturally insular in Miami during the 1970s, bonded together by the trauma of exile. What s more, it seemed that practically everyone was Cuban my teachers, my classmates, the mechanic, the bus driver. I didn t grow up feeling different or treated as a minority. The few kids who got picked on in my grade school were the ones with freckles and funny last names like Dawson and O Neil.', 'Ao relatar suas vivências, o autor destaca o(a):', NULL),
('Basico', 7, '(Enem 2022)', 'Two hundred years ago, Jane Austen lived in a world where single men boasted vast estates; single ladies were expected to speak several languages, sing and play the piano. In both cases, it was, of course, advantageous if you looked good too. So, how much has – or hasn t – changed? Dating apps opaquely outline the demands of today s relationship market; users ruminate long and hard over their choice of pictures and what they write in their biographies to hook in potential lovers, and that s just your own profile. What do you look for in a future partner s profile – potential signifiers of a popular personality, a good job, a nice car? These apps are a poignant reminder of the often classist attitudes we still adopt, as well as the financial and aesthetic expectations we demand from potential partners.', 'O texto aborda relações interpessoais com o objetivo de:', NULL),
('Basico', 8, '(Enem 2020)', NULL, 'No cartum, o estudante faz uma pergunta usando turn this thing on por:', 'https://storage.googleapis.com/novo-blog-wordpress/2024/05/e652e2f6-unnamed-30.png'),
('Basico', 9, '(Enem 2022)', 'A Teen s View of Social Media Instagram is made up of all photos and videos. There is the home page that showcases the posts from people you follow, an explore tab which offers posts from accounts all over the world, and your own page, with a notification tab to show who likes and comments on your posts. It has some downsides though. It is known to make many people feel insecure or down about themselves because the platform showcases the highlights of everyone s lives, while rarely showing the negatives. This can make one feel like their life is not going as well as others, contributing to the growing rates of anxiety or depression in many teens today. There is an underlying desire for acceptance through the number of likes or followers one has.', 'O termo downsides introduz a ideia de que o Instagram é responsável por:', NULL),
('Basico', 10, '(Enem 2021)', 'Becomin Back in the ancestral homeland of Michelle Obama, black women were rarely granted the honorific Miss or Mrs., but were addressed by their first name, or simply as gal or auntie or worse. This so openly demeaned them that many black women, long after they had left the South, refused to answer if called by their first name. A mother and father in 1970s Texas named their newborn Miss so that white people would have no choice but to address their daughter by that title. Black women were meant for the field or the kitchen, or for use as they saw fit. They were, by definition, not ladies. The very idea of a black woman as first lady of the land, well, that would have been unthinkable.', 'A crítica do livro de memórias de Michelle Obama, ex-primeira-dama dos EUA, aborda a história das relações humanas na cidade natal da autora. Nesse contexto, o uso do vocábulo unthinkable ressalta que:', NULL),
('Basico', 11, '(Enem 2020)', 'A Minor Bird I have wished a bird would fly away, And not sing by my house all day; Have clapped my hands at him from the door When it seemed as if I could bear no more. The fault must partly have been in me. The bird was not to blame for his key. And of course there must be something wrong In wanting to silence any song.', 'No poema de Robert Frost, as palavras fault e blame revelam por parte do eu lírico uma:', NULL),
('Basico', 12, '(Enem 2011)', NULL, 'Na fase escolar, é prática comum que os professores passem atividades extraclasse e marquem uma data para que as mesmas sejam entregues para correção. No caso da cena da charge, a professora ouve uma estudante apresentando argumentos para:', 'https://d2q576s0wzfxtl.cloudfront.net/2017/08/08150628/questao92.enem2011.png'),
('Basico', 13, '(Enem 2012)', 'Quotes Of The Day Friday, Sep. 02, 2011 There probably was a shortage of notaries in my town. I m the kind of guy who never reads the letter X or anything, even though the man gave it to me three times, No, said the other, We have to find a way to show you you re wrong, but you re also right, we can put this question in a folder. It s already obvious that he never read that text, and it s hard to believe he was also wrong about the text.', 'Em relação à charge, a parte em que a fala We have to find a way to show you you re wrong revela um tipo de discurso:', NULL),
('Basico', 14, '(Enem 2013)', 'The best teachers are those who show you where to look, but don t tell you what to see.', 'A frase apresentada expressa a ideia de que os melhores professores:', NULL),
('Basico', 15, '(Enem 2014)', 'The advertisement is a powerful tool for companies to promote their products. It is a way to communicate with the public and make them aware of the products and services that the company offers. The advertisement can be in the form of a poster, a commercial on TV, a radio jingle, or a banner on a website. The advertisement can be used to inform the public about new products, services, or promotions. It can also be used to persuade the public to buy a product or service. The advertisement can be used to create brand awareness and build brand loyalty. The advertisement can be used to reach a large audience and increase sales. The advertisement can be used to create a positive image of the company and its products. The advertisement can be used to create a competitive advantage for the company.', 'O texto tem como objetivo:', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_ec534fc94ba9ef0ebf3ad516d3ee6884_101825.jpg.jpeg');

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES 
(1, 'Basico', 'a) necessidade de acessar informações confiáveis.', FALSE),
(1, 'Basico', 'b) dificuldade de conciliar diferentes anseios.', TRUE),
(1, 'Basico', 'c) desejo de dominar novas tecnologias.', FALSE),
(1, 'Basico', 'd) desafio de permanecer imparcial.', FALSE),
(1, 'Basico', 'e) vontade de ler notícias positivas.', FALSE),
(2, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(2, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(2, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(2, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(2, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(3, 'Basico', 'a) anunciar mercadorias em promoção.', TRUE),
(3, 'Basico', 'b) pedir para uma pessoa se retirar.', FALSE),
(3, 'Basico', 'c) comprar produtos fora de moda.', FALSE),
(3, 'Basico', 'd) indicar recessão na economia.', FALSE),
(3, 'Basico', 'e) chamar alguém em voz alta.', FALSE),
(4, 'Basico', 'a) revolta com a falta de sorte.', FALSE),
(4, 'Basico', 'b) receio pelo futuro do casamento.', FALSE),
(4, 'Basico', 'c) gosto pela prática da leitura.', TRUE),
(4, 'Basico', 'd) entusiasmo com os livros de terror.', FALSE),
(4, 'Basico', 'e) rejeição ao novo tipo de residência.', FALSE),
(5, 'Basico', 'a) medo da morte.', FALSE),
(5, 'Basico', 'b) ideia de conexão.', TRUE),
(5, 'Basico', 'c) conceito de solidão.', FALSE),
(5, 'Basico', 'd) risco de devastação.', FALSE),
(5, 'Basico', 'e) necessidade de empatia.', FALSE),
(6, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(6, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(6, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(6, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(6, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(7, 'Basico', 'a) problematizar o papel de gênero em casamentos modernos.', FALSE),
(7, 'Basico', 'b) apontar a relevância da educação formal na escolha de parceiros.', FALSE),
(7, 'Basico', 'c) comparar a expectativa de parceiros amorosos em épocas distintas.', TRUE),
(7, 'Basico', 'd) discutir o uso de aplicativos para proporcionar encontros românticos.', FALSE),
(7, 'Basico', 'e) valorizar a importância da aparência física na seleção de pretendentes.', FALSE),
(8, 'Basico', 'a) suspeitar que o colega está com seu material por engano.', FALSE),
(8, 'Basico', 'b) duvidar que o colega possa se tornar um bom aluno.', FALSE),
(8, 'Basico', 'c) desconfiar que o livro levado é de outra matéria.', FALSE),
(8, 'Basico', 'd) entender como desligada a postura do colega.', FALSE),
(8, 'Basico', 'e) desconhecer como usar um livro impresso.', TRUE),
(9, 'Basico', 'a) oferecer recursos de fotografia.', FALSE),
(9, 'Basico', 'b) divulgar problemas dos usuários.', FALSE),
(9, 'Basico', 'c) estimular aceitação dos seguidores.', FALSE),
(9, 'Basico', 'd) provocar ansiedade nos adolescentes.', TRUE),
(9, 'Basico', 'e) aproximar pessoas ao redor do mundo.', FALSE),
(10, 'Basico', 'a) a ascensão social era improvável.', TRUE),
(10, 'Basico', 'b) a mudança de nome era impensável.', FALSE),
(10, 'Basico', 'c) a origem do indivíduo era irrelevante.', FALSE),
(10, 'Basico', 'd) o trabalho feminino era inimaginável.', FALSE),
(10, 'Basico', 'e) o comportamento parental era irresponsável.', FALSE),
(11, 'Basico', 'a) culpa por não poder cuidar do pássaro.', FALSE),
(11, 'Basico', 'b) atitude errada por querer matar o pássaro.', FALSE),
(11, 'Basico', 'c) necessidade de entender o silêncio do pássaro.', FALSE),
(11, 'Basico', 'd) sensibilização com relação à natureza do pássaro.', TRUE),
(11, 'Basico', 'e) irritação quanto à persistência do canto do pássaro.', FALSE),
(12, 'Basico', 'a) discutir sobre o conteúdo do seu trabalho já entregue.', FALSE),
(12, 'Basico', 'b) elogiar o tema proposto para o relatório solicitado.', FALSE),
(12, 'Basico', 'c) sugerir temas para novas pesquisas e relatórios.', FALSE),
(12, 'Basico', 'd) reclamar do curto prazo para entrega do trabalho.', FALSE),
(12, 'Basico', 'e) convencer de que fez o relatório solicitado.', TRUE),
(13, 'Basico', 'a) enfatizar a discriminação contra os jovens britânicos e suas famílias.', FALSE),
(13, 'Basico', 'b) criticar as ações agressivas demonstradas nos tumultos pelos jovens.', FALSE),
(13, 'Basico', 'c) estabelecer relação entre a falta de limites dos jovens e o excesso de amor.', FALSE),
(13, 'Basico', 'd) reforçar a ideia de que os jovens precisam de amor, mas também de firmeza.', TRUE),
(13, 'Basico', 'e) escrever o tipo de amor que gera problemas às famílias de jovens britânicos.', FALSE),
(14, 'Basico', 'a) temem quem as amedronta.', FALSE),
(14, 'Basico', 'b) aprendem com o que vivem.', TRUE),
(14, 'Basico', 'c) amam aqueles que as aceitam.', FALSE),
(14, 'Basico', 'd) são gentis quando respeitadas.', FALSE),
(14, 'Basico', 'e) ridicularizam quem as intimida.', FALSE),
(15, 'Basico', 'a) conscientizar sobre a necessidade de otimização do consumo.', TRUE),
(15, 'Basico', 'b) divulgar espaços publicitários de grande visibilidade.', FALSE),
(15, 'Basico', 'c) sensibilizar para a conservação do patrimônio público.', FALSE),
(15, 'Basico', 'd) apresentar uma forma mais econômica de fazer publicidade.', FALSE),
(15, 'Basico', 'e) denunciar possíveis danos decorrentes de atos de vandalismo.', FALSE);

-- Nível Intermediário
INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Intermediario', 1, '(Enem PPL 2014)', NULL, 'Implementar políticas adequadas de alimentação e nutrição é uma meta prioritária em vários países do mundo. A partir da campanha If you can t read it, why eat it?, os leitores são alertados para o perigo de:', NULL),
('Intermediario', 2, '(Enem 2014)', 'Tennessee Mountain Properties: Description- Own a renovated house for less than $290 per month!!!!!!!! New windows, siding, flooring (laminate throughout and tile in entry way and bathroom), kitchen cabinets, counter top, back door, fresh paint and laundry on main floor. Heat bills are very low due to a good solid house and an energy efficient furnace. Disponível em: www.freerealestaeads.net. Acesso em: 30 nov. 2011 (adaptado).', 'Em jornais, há diversos anúncios que servem aos leitores. O conteúdo do anúncio veiculado por este texto interessará a alguém que esteja procurando:', NULL),
('Intermediario', 3, '(Brasil Escola)', NULL, 'Qual das alternativas apresenta apenas advérbios de tempo?', NULL),
('Intermediario', 4, '(UNIP)', NULL, 'It s ________ honor to meet ________ young lady from Sweden.', NULL),
('Intermediario', 5, '(Enem PPL 2013)', NULL, 'Tirinhas são construídas a partir de contextos sociais e podem promover reflexões diversas. Essa tirinha provoca no leitor uma reflexão acerca da:', NULL),
('Intermediario', 6, '(Enem PPL 2011)', NULL, 'Ao estabelecer uma relação entre a Matemática e o blues a partir da opinião pessoal de um dos rapazes, a charge sugere que:', NULL),
('Intermediario', 7, '(Enem 2014)', 'The Road Not Taken (by Robert Frost): Two roads diverged in a wood, and I — I took the one less traveled by, And that has made all the difference. Disponível em: www.poetryfoundation.org. Acesso em: 29 nov. 2011 (fragmento).', 'Estes são os versos finais do famoso poema The Road Not Taken, do poeta americano Robert Frost. Levando-se em consideração que a vida é comumente metaforizada como uma viagem, esses versos indicam que o autor:', NULL),
('Intermediario', 8, '(Enem PPL 2010)', 'Crystal Ball: Come see your life in my crystal glass — Twenty-five cents is all you pay Let me look into your past — Here s what you had for lunch today: Tuna salad and mashed potatoes, Collard greens pea soup and apple juice, Chocolate milk and lemon mousse. You admit I ve got told it all? Well, I know it, I confess, Not by looking, in my ball, But just by looking at your dress. SILVERSTEIN, S. Falling up. New York: Harper Collins Publishers, 1996.', 'A curiosidade a respeito do futuro pode exercer um fascínio peculiar sobre algumas pessoas, a ponto de colocá-las em situações inusitadas. Na letra da música Crystal Ball, essa situação fica evidente quando é revelado à pessoa que ela:', NULL),
('Intermediario', 9, '(Unesp)', NULL, 'Indique a alternativa que expressa o mesmo significado de: When children watch TV, they encounter a wide range of places, people, and information.', NULL),
('Intermediario', 10, '(Enem, 2020)', 'Finally, Aisha finished with her customer and asked what colour Ifemelu wanted for her hair attachments. “Colour four.” “Not good colour,” Aisha said promptly. “That s what I use.” “It look dirty. You don t want colour one?” “Colour one it too black. It looks fake,” Ifemelu said, loosening her headwrap. “Sometimes I use colour two, but colour four is closest to my natural colour.” […] She touched Ifemelu s hair. “Why you don t have relaxer?” “I like my hair the way God made it.” “But how do you comb it? Hard to comb,” Aisha said. Ifemelu had brought her own comb. She gently combed her hair, dense, soft and tightly coiled, until it framed her head like a halo. “It s not hard to comb if you moisturize it properly,” she said, slipping into the coaxing tone of the proselytizer that she used whenever she was trying to convince other black women about the merits of wearing their hair natural. Aisha snorted; she clearly could not understand why anybody would choose to suffer through combing natural hair, plucked a little attachment from the pile on the table ad began deftly to twist. ADICHIE, C. Americanah: A novel. New York: Anchor Books, 2013.', 'A passagem do romance da escritora nigeriana traz um diálogo entre duas mulheres negras: a cabeleireira, Aisha, e a cliente, Ifemelu. O posicionamento da cliente é sustentado por argumentos que:', NULL),
('Intermediario', 11, '(Enem, 2020)', NULL, 'Os recursos usados nesse pôster de divulgação de uma campanha levam o leitor a refletir sobre a necessidade de:', NULL),
('Intermediario', 12, '(Enem em inglês, 2018)', 'Don t write in English, they said, English is not your mother tongue… …The language I speak Becomes mine, its distortions, its queerness All mine, mine alone, it is half English, half Indian, funny perhaps, but it is honest, It is as human as I am human… …It voices my joys, my longings my Hopes… (Kamala Das, 1965:10) GARGESH, R. South Asian Englishes. In: KACHRU, B.B.; KACHRU, Y.; NELSON, C.L. (Eds.). The Handbook of World English. Singapore: Blackwell, 2006', 'A poetisa Kamala Das, como muitos escritores indianos, escreve suas obras em inglês, apesar de essa não ser sua primeira língua. Nesses versos, ela:', NULL),
('Intermediario', 13, '(Enem/2018)', 'Is it your opinion, Winston, that the past has real existence?/ [...] O\Brien smiled faintly. \I will put it more precisely. Does the past exist concretely, in space? Is there somewhere or other a place, a world of solid objects, where the past is still happening?\ \No.\ \Then where does the past exist, if at all? \In records. It is written down.\ \In records. And — —?\ \In the mind. In human memories.\ \In memory. Very well, then. We, the Party, control all records, and we control all memories. Then we control the past, do we not?\ ORWELL. G, Nineteen Eighty-Four. New York: Signet Classics, 1977', 'O romance 1984 descreve os perigos de um Estado totalitário. A ideia evidenciada nessa passagem é que o controle do Estado se dá por meio do(a):', NULL),
('Intermediario', 14, '(Enem 2012)', 'DONAR. Disponível em: http://politicalgraffiti.wordpress.com. Acesso em: 17 ago. 2011.', 'Cartuns são produzidos com o intuito de satirizar comportamentos humanos e assim oportunizam a reflexão sobre nossos próprios comportamentos e atitudes. Nesse cartum, a linguagem utilizada pelos personagens em uma conversa em inglês evidencia a:', NULL),
('Intermediario', 15, '(Enem/2018)', 'Lava Mae: Creating Showers on Wheels for the Homeless- San Francisco, according to recent city numbers, has 4,300 people living on the streets. Among the many problems the homeless face is little or no access to showers. San Francisco only has about 16 to 20 shower stalls to accommodate them. But Doniece Sandoval has made it her mission to change that. The 51-year-old former marketing executive started Lava Mae, a sort of showers on wheels, a new project that aims to turn decommissioned city buses into shower stations for the homeless. Each bus will have two shower stations and Sandoval expects that they\ll be able to provide 2,000 showers a week. ANDREANO, C. Dísponível em: abcnews.go.com. Acesso: 26 jun. 2015 (adaptado).', 'A relação dos vocábulos shower, bus e homeless, no texto, refere-se a:', NULL);

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Intermediario', 'a) acessarem informações equivocadas sobre a formulação química de alimentos empacotados.', FALSE),
(1, 'Intermediario', 'b) consumirem alimentos industrializados sem o interesse em conhecer a sua composição.', TRUE),
(1, 'Intermediario', 'c) desenvolverem problemas de saúde pela falta de conhecimento a respeito do teor dos alimentos.', FALSE),
(1, 'Intermediario', 'd) incentivarem crianças a ingerirem grande quantidade de alimentos processados e com conservantes.', FALSE),
(1, 'Intermediario', 'e) ignorarem o aumento constante da obesidade causada pela má alimentação na fase de desenvolvimento da crianças.', FALSE),
(2, 'Intermediario', 'a) emprego no setor imobiliário.', FALSE),
(2, 'Intermediario', 'b) imóvel residencial para compra.', TRUE),
(2, 'Intermediario', 'c) serviço de reparos em domicílio.', FALSE),
(2, 'Intermediario', 'd) pessoa para trabalho doméstico.', FALSE),
(2, 'Intermediario', 'e) curso de decorador de interiores.', FALSE),
(3, 'Intermediario', 'a) already, always, then, above.', FALSE),
(3, 'Intermediario', 'b) first, here, rarely, yet.', FALSE),
(3, 'Intermediario', 'c) below, before, never, hard.', FALSE),
(3, 'Intermediario', 'd) first, already, usually, yet.', FALSE),
(3, 'Intermediario', 'e) lately, still, next, finaly.', TRUE),
(4, 'Intermediario', 'a) a / an.', FALSE),
(4, 'Intermediario', 'b) an / an.', FALSE),
(4, 'Intermediario', 'c) a / a.', FALSE),
(4, 'Intermediario', 'd) an / a.', TRUE),
(5, 'Intermediario', 'a) divisão de espaço com os pais.', FALSE),
(5, 'Intermediario', 'b) perda da atenção dos pais.', FALSE),
(5, 'Intermediario', 'c) semelhança com os pais.', TRUE),
(5, 'Intermediario', 'd) ausência dos pais.', FALSE),
(5, 'Intermediario', 'e) submissão aos pais.', FALSE),
(6, 'Intermediario', 'a) o blues, com seu ritmo depressivo, alivia o sentimento causado pela Matemática.', TRUE),
(6, 'Intermediario', 'b) as canções iniciadas com a contagem de 1 a 4 fazem lembrar o blues.', FALSE),
(6, 'Intermediario', 'c) as canções devem se iniciar com a contagem de 1 a 4 para se tornarem tristes.', FALSE),
(6, 'Intermediario', 'd) o blues, assim como a Matemática, consegue despertar um sentimento inspirador.', FALSE),
(6, 'Intermediario', 'e) o sentimento despertado pela Matemática serve como motivação para o blues.', FALSE),
(7, 'Intermediario', 'a) festeja o fato de ter sido ousado na escolha que fez em sua vida.', TRUE),
(7, 'Intermediario', 'b) lamenta por ter sido um viajante que encontrou muitas bifurcações.', FALSE),
(7, 'Intermediario', 'c) viaja muito pouco e que essa escolha fez toda a diferença em sua vida.', FALSE),
(7, 'Intermediario', 'd) reconhece que as dificuldades em sua vida foram todas superadas.', FALSE),
(7, 'Intermediario', 'e) percorre várias estradas durante as diferentes fases de sua vida.', FALSE),
(8, 'Intermediario', 'a) recebeu uma boa notícia.', FALSE),
(8, 'Intermediario', 'b) ganhou um colar de pedras.', FALSE),
(8, 'Intermediario', 'c) se sujou durante o almoço.', TRUE),
(8, 'Intermediario', 'd) comprou vestidos novos.', FALSE),
(8, 'Intermediario', 'e) encontrou uma moeda.', FALSE),
(9, 'Intermediario', 'a) When children watch TV, a wide range of places, people, and information will be encounter.', FALSE),
(9, 'Intermediario', 'b) When children watch TV, a wide range of places, people, and information are encountered.', FALSE),
(9, 'Intermediario', 'c) When children watch TV, a wide range of places, people, and information is encountered.', TRUE),
(9, 'Intermediario', 'd) When TV was watched, a wide range of places, people, and information are encountered by children.', FALSE),
(9, 'Intermediario', 'e) A wide range of places, people, and information will be encountered when children watched TV.', FALSE),
(10, 'Intermediario', 'a) reforçam um padrão de beleza.', FALSE),
(10, 'Intermediario', 'b) retratam um conflito de gerações.', FALSE),
(10, 'Intermediario', 'c) revelam uma atitude de resistência.', TRUE),
(10, 'Intermediario', 'd) demonstram uma postura de imaturidade.', FALSE),
(10, 'Intermediario', 'e) evidenciam uma mudança de comportamento.', FALSE),
(11, 'Intermediario', 'a) criticar o tipo de tratamento dado à mulher.', TRUE),
(11, 'Intermediario', 'b) rever o desempenho da mulher no trabalho.', FALSE),
(11, 'Intermediario', 'c) questionar a sobrecarga de atribuições da mulher.', FALSE),
(11, 'Intermediario', 'd) analisar as pesquisas acerca dos direitos da mulher.', FALSE),
(11, 'Intermediario', 'e) censurar a mulher pelo uso de determinadas palavras.', FALSE),
(12, 'Intermediario', 'a) usa a língua inglesa como efeito humorístico.', FALSE),
(12, 'Intermediario', 'b) recorre a vozes de vários escritores ingleses.', FALSE),
(12, 'Intermediario', 'c) adverte sobre o uso distorcido da língua inglesa.', FALSE),
(12, 'Intermediario', 'd) demonstra consciência de sua identidade linguística.', TRUE),
(12, 'Intermediario', 'e) reconhece a incompreensão na sua maneira de falar inglês.', FALSE),
(13, 'Intermediario', 'a) boicote a ideais libertários.', FALSE),
(13, 'Intermediario', 'b) veto ao culto das tradições.', FALSE),
(13, 'Intermediario', 'c) poder sobre memórias e registros.', TRUE),
(13, 'Intermediario', 'd) censura a produções orais e escritas.', FALSE),
(13, 'Intermediario', 'e) manipulação de pensamentos individuais.', FALSE),
(14, 'Intermediario', 'a) predominância do uso da linguagem informal sobre a língua padrão.', FALSE),
(14, 'Intermediario', 'b) dificuldade de reconhecer a existência de diferentes usos da linguagem.', TRUE),
(14, 'Intermediario', 'c) aceitação dos regionalismos utilizados por pessoas de diferentes lugares.', FALSE),
(14, 'Intermediario', 'd) necessidade de estudo da língua inglesa por parte dos personagens.', FALSE),
(14, 'Intermediario', 'e) facilidade de compreensão entre falantes com sotaques distintos.', FALSE),
(15, 'Intermediario', 'a) empregar moradores de rua em lava a jatos para ônibus.', FALSE),
(15, 'Intermediario', 'b) comissionar sem-teto para dirigir os ônibus da cidade.', FALSE),
(15, 'Intermediario', 'c) exigir das autoridades que os ônibus municipais tenham banheiros.', FALSE),
(15, 'Intermediario', 'd) abrigar dois mil moradores de rua em ônibus que foram adaptados.', FALSE),
(15, 'Intermediario', 'e) criar acesso a banhos gratuitos para moradores de rua.', TRUE);
