CREATE DATABASE portal_ingles10;

CREATE TYPE nivel_enum AS ENUM ('Basico', 'Intermediario', 'Avancado', 'Proficiente');

CREATE TABLE simulados (
    id SERIAL PRIMARY KEY, 
    nivel nivel_enum NOT NULL,
    numero_pergunta INT NOT NULL CHECK (numero_pergunta BETWEEN 1 AND 15), 
    titulo VARCHAR(50) NOT NULL, 
    texto_pergunta TEXT,
    pergunta_texto TEXT, 
    url VARCHAR(255), 
    UNIQUE (nivel, numero_pergunta)
);
CREATE TABLE alternativas (
    id SERIAL PRIMARY KEY, 
    id_pergunta INT NOT NULL, 
    nivel nivel_enum NOT NULL,
    texto_alternativa TEXT NOT NULL, 
    correta BOOLEAN NOT NULL, 
    FOREIGN KEY (id_pergunta) REFERENCES simulados(id) ON DELETE CASCADE
);

-- Nível Básico

INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Basico', 1, '(Enem 2021)', NULL, 'A presença de at odds with na fala da personagem do cartum revela o(a):', 'https://blogger.googleusercontent.com/img/a/AVvXsEhCvRSIDqYEwlUR-cW3xR4EpXkw35jJeGURtAx8e4uvrtKEkBvhGIM13Be357bLKauia5nZqyvEoG6-nkT9W8dIbSmF6UIq_zG2SDzKclfJhtK3WilvF0QDtksY6qDgMH7Z-eTibyCaY5oRWwpL7tFwsE8miV0qhofs9rMicZkzCusC_1_Ym0zlEjoL=s600'),
('Basico', 2, '(Enem 2019)', 'A pet is certainly a great friend. After a difficult day, pet owners quite literally feel the love. In fact, for nearly 25 years, research has shown that living with pets provides certain health benefits. Pets help lower blood pressure and lessen anxiety. They boost our immunity. They can even help you get dates. Allergy Fighters A growing number of studies have suggested that kids growing up in a home with furred animals will have less risk of allergies and asthma. Date Magnets Dogs are great for making love connections. Forget Internet matchmaking – a dog is a natural conversation starter. Dogs for the Aged Walking a dog or just caring for a pet – for elderly people who are able – can provide exercise and companionship. Good for Mind and Soul Like any enjoyable activity, playing with a dog can elevate levels of serotonin and dopamine – nerve transmitters that are known to have pleasurable and calming properties. Good for the Heart Heart attack patients who have pets survive longer than those without, according to several studies.', 'Ao discutir sobre a influência de animais de estimação no bem-estar do ser humano, a autora, a fim de fortalecer seus argumentos, utiliza palavras e expressões como research, a growing number of research e several studies com o objetivo de:', NULL),
('Basico', 3, '(Enem 2016)', 'BOGOF is used as a noun as in There are some great bogofs on at the supermarket or an adjective, usually with a word such as offer or deal — there are some great bogof offers in store. When you combine the first letters of the words in a phrase or the name of an organisation, you have an acronym. Acronyms are spoken as a word so NATO (North Atlantic Treaty Organisation) is not pronounced N-A-T-O. We say NATO. Bogof, when said out loud, is quite comical for a native speaker, as it sounds like an insult, Bog off! meaning go away, leave me alone, slightly childish and a little old-fashioned. BOGOF is the best-known of the supermarket marketing strategies. The concept was first imported from the USA during the 1970s recession, when food prices were very high. It came back into fashion in the late 1990s, led by big supermarket chains trying to gain a competitive advantage over each other. Consumers were attracted by the idea that they could get something for nothing. Who could possibly say no?', 'Considerando-se as informações do texto, a expressão bogof é usada para:', NULL),
('Basico', 4, '(Enem 2022)', NULL, 'Na tirinha, o comportamento da mulher expressa:', 'https://kuadro-static.storage.googleapis.com/050548bae767435282242b1c404c6348/0000.png'),
('Basico', 5, '(Enem 2023)', 'No man is an island, Entire of itself; Every man is a piece of the continent, A part of the main. [...] Any man s death diminishes me, Because I am involved in mankind.', 'Nesse poema, a expressão No man is an island ressalta o(a):', NULL),
('Basico', 6, '(Enem 2022)', 'As my official bio reads, I was made in Cuba, assembled in Spain, and imported to the United States – meaning my mother, seven months pregnant, and the rest of my family arrived as exiles from Cuba to Madrid, where I was born. Less than two months later, we emigrated once more and settled in New York City, then eventually in Miami, where I was raised and educated. Although technically we lived in the United States, the Cuban community was culturally insular in Miami during the 1970s, bonded together by the trauma of exile. What s more, it seemed that practically everyone was Cuban my teachers, my classmates, the mechanic, the bus driver. I didn t grow up feeling different or treated as a minority. The few kids who got picked on in my grade school were the ones with freckles and funny last names like Dawson and O Neil.', 'Ao relatar suas vivências, o autor destaca o(a):', NULL),
('Basico', 7, '(Enem 2022)', 'Two hundred years ago, Jane Austen lived in a world where single men boasted vast estates; single ladies were expected to speak several languages, sing and play the piano. In both cases, it was, of course, advantageous if you looked good too. So, how much has – or hasn t – changed? Dating apps opaquely outline the demands of today s relationship market; users ruminate long and hard over their choice of pictures and what they write in their biographies to hook in potential lovers, and that s just your own profile. What do you look for in a future partner s profile – potential signifiers of a popular personality, a good job, a nice car? These apps are a poignant reminder of the often classist attitudes we still adopt, as well as the financial and aesthetic expectations we demand from potential partners.', 'O texto aborda relações interpessoais com o objetivo de:', NULL),
('Basico', 8, '(Enem 2020)', NULL, 'No cartum, o estudante faz uma pergunta usando turn this thing on por:', 'https://storage.googleapis.com/novo-blog-wordpress/2024/05/e652e2f6-unnamed-30.png'),
('Basico', 9, '(Enem 2022)', 'A Teen s View of Social Media Instagram is made up of all photos and videos. There is the home page that showcases the posts from people you follow, an explore tab which offers posts from accounts all over the world, and your own page, with a notification tab to show who likes and comments on your posts. It has some downsides though. It is known to make many people feel insecure or down about themselves because the platform showcases the highlights of everyone s lives, while rarely showing the negatives. This can make one feel like their life is not going as well as others, contributing to the growing rates of anxiety or depression in many teens today. There is an underlying desire for acceptance through the number of likes or followers one has.', 'O termo downsides introduz a ideia de que o Instagram é responsável por:', NULL),
('Basico', 10, '(Enem 2021)', 'Becomin Back in the ancestral homeland of Michelle Obama, black women were rarely granted the honorific Miss or Mrs., but were addressed by their first name, or simply as gal or auntie or worse. This so openly demeaned them that many black women, long after they had left the South, refused to answer if called by their first name. A mother and father in 1970s Texas named their newborn Miss so that white people would have no choice but to address their daughter by that title. Black women were meant for the field or the kitchen, or for use as they saw fit. They were, by definition, not ladies. The very idea of a black woman as first lady of the land, well, that would have been unthinkable.', 'A crítica do livro de memórias de Michelle Obama, ex-primeira-dama dos EUA, aborda a história das relações humanas na cidade natal da autora. Nesse contexto, o uso do vocábulo unthinkable ressalta que:', NULL),
('Basico', 11, '(Enem 2020)', 'A Minor Bird I have wished a bird would fly away, And not sing by my house all day; Have clapped my hands at him from the door When it seemed as if I could bear no more. The fault must partly have been in me. The bird was not to blame for his key. And of course there must be something wrong In wanting to silence any song.', 'No poema de Robert Frost, as palavras fault e blame revelam por parte do eu lírico uma:', NULL),
('Basico', 12, '(Enem 2011)', NULL, 'Na fase escolar, é prática comum que os professores passem atividades extraclasse e marquem uma data para que as mesmas sejam entregues para correção. No caso da cena da charge, a professora ouve uma estudante apresentando argumentos para:', 'https://d2q576s0wzfxtl.cloudfront.net/2017/08/08150628/questao92.enem2011.png'),
('Basico', 13, '(Enem 2012)', 'Quotes Of The Day Friday, Sep. 02, 2011 There probably was a shortage of notaries in my town. I m the kind of guy who never reads the letter X or anything, even though the man gave it to me three times, No, said the other, We have to find a way to show you you re wrong, but you re also right, we can put this question in a folder. It s already obvious that he never read that text, and it s hard to believe he was also wrong about the text.', 'Em relação à charge, a parte em que a fala We have to find a way to show you you re wrong revela um tipo de discurso:', NULL),
('Basico', 14, '(Enem 2013)', 'The best teachers are those who show you where to look, but don t tell you what to see.', 'A frase apresentada expressa a ideia de que os melhores professores:', NULL),
('Basico', 15, '(Enem 2014)', 'The advertisement is a powerful tool for companies to promote their products. It is a way to communicate with the public and make them aware of the products and services that the company offers. The advertisement can be in the form of a poster, a commercial on TV, a radio jingle, or a banner on a website. The advertisement can be used to inform the public about new products, services, or promotions. It can also be used to persuade the public to buy a product or service. The advertisement can be used to create brand awareness and build brand loyalty. The advertisement can be used to reach a large audience and increase sales. The advertisement can be used to create a positive image of the company and its products. The advertisement can be used to create a competitive advantage for the company.', 'O texto tem como objetivo:', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_ec534fc94ba9ef0ebf3ad516d3ee6884_101825.jpg.jpeg');

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES 
(1, 'Basico', 'a) necessidade de acessar informações confiáveis.', FALSE),
(1, 'Basico', 'b) dificuldade de conciliar diferentes anseios.', TRUE),
(1, 'Basico', 'c) desejo de dominar novas tecnologias.', FALSE),
(1, 'Basico', 'd) desafio de permanecer imparcial.', FALSE),
(1, 'Basico', 'e) vontade de ler notícias positivas.', FALSE),
(2, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(2, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(2, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(2, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(2, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(3, 'Basico', 'a) anunciar mercadorias em promoção.', TRUE),
(3, 'Basico', 'b) pedir para uma pessoa se retirar.', FALSE),
(3, 'Basico', 'c) comprar produtos fora de moda.', FALSE),
(3, 'Basico', 'd) indicar recessão na economia.', FALSE),
(3, 'Basico', 'e) chamar alguém em voz alta.', FALSE),
(4, 'Basico', 'a) revolta com a falta de sorte.', FALSE),
(4, 'Basico', 'b) receio pelo futuro do casamento.', FALSE),
(4, 'Basico', 'c) gosto pela prática da leitura.', TRUE),
(4, 'Basico', 'd) entusiasmo com os livros de terror.', FALSE),
(4, 'Basico', 'e) rejeição ao novo tipo de residência.', FALSE),
(5, 'Basico', 'a) medo da morte.', FALSE),
(5, 'Basico', 'b) ideia de conexão.', TRUE),
(5, 'Basico', 'c) conceito de solidão.', FALSE),
(5, 'Basico', 'd) risco de devastação.', FALSE),
(5, 'Basico', 'e) necessidade de empatia.', FALSE),
(6, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(6, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(6, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(6, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(6, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(7, 'Basico', 'a) problematizar o papel de gênero em casamentos modernos.', FALSE),
(7, 'Basico', 'b) apontar a relevância da educação formal na escolha de parceiros.', FALSE),
(7, 'Basico', 'c) comparar a expectativa de parceiros amorosos em épocas distintas.', TRUE),
(7, 'Basico', 'd) discutir o uso de aplicativos para proporcionar encontros românticos.', FALSE),
(7, 'Basico', 'e) valorizar a importância da aparência física na seleção de pretendentes.', FALSE),
(8, 'Basico', 'a) suspeitar que o colega está com seu material por engano.', FALSE),
(8, 'Basico', 'b) duvidar que o colega possa se tornar um bom aluno.', FALSE),
(8, 'Basico', 'c) desconfiar que o livro levado é de outra matéria.', FALSE),
(8, 'Basico', 'd) entender como desligada a postura do colega.', FALSE),
(8, 'Basico', 'e) desconhecer como usar um livro impresso.', TRUE),
(9, 'Basico', 'a) oferecer recursos de fotografia.', FALSE),
(9, 'Basico', 'b) divulgar problemas dos usuários.', FALSE),
(9, 'Basico', 'c) estimular aceitação dos seguidores.', FALSE),
(9, 'Basico', 'd) provocar ansiedade nos adolescentes.', TRUE),
(9, 'Basico', 'e) aproximar pessoas ao redor do mundo.', FALSE),
(10, 'Basico', 'a) a ascensão social era improvável.', TRUE),
(10, 'Basico', 'b) a mudança de nome era impensável.', FALSE),
(10, 'Basico', 'c) a origem do indivíduo era irrelevante.', FALSE),
(10, 'Basico', 'd) o trabalho feminino era inimaginável.', FALSE),
(10, 'Basico', 'e) o comportamento parental era irresponsável.', FALSE),
(11, 'Basico', 'a) culpa por não poder cuidar do pássaro.', FALSE),
(11, 'Basico', 'b) atitude errada por querer matar o pássaro.', FALSE),
(11, 'Basico', 'c) necessidade de entender o silêncio do pássaro.', FALSE),
(11, 'Basico', 'd) sensibilização com relação à natureza do pássaro.', TRUE),
(11, 'Basico', 'e) irritação quanto à persistência do canto do pássaro.', FALSE),
(12, 'Basico', 'a) discutir sobre o conteúdo do seu trabalho já entregue.', FALSE),
(12, 'Basico', 'b) elogiar o tema proposto para o relatório solicitado.', FALSE),
(12, 'Basico', 'c) sugerir temas para novas pesquisas e relatórios.', FALSE),
(12, 'Basico', 'd) reclamar do curto prazo para entrega do trabalho.', FALSE),
(12, 'Basico', 'e) convencer de que fez o relatório solicitado.', TRUE),
(13, 'Basico', 'a) enfatizar a discriminação contra os jovens britânicos e suas famílias.', FALSE),
(13, 'Basico', 'b) criticar as ações agressivas demonstradas nos tumultos pelos jovens.', FALSE),
(13, 'Basico', 'c) estabelecer relação entre a falta de limites dos jovens e o excesso de amor.', FALSE),
(13, 'Basico', 'd) reforçar a ideia de que os jovens precisam de amor, mas também de firmeza.', TRUE),
(13, 'Basico', 'e) escrever o tipo de amor que gera problemas às famílias de jovens britânicos.', FALSE),
(14, 'Basico', 'a) temem quem as amedronta.', FALSE),
(14, 'Basico', 'b) aprendem com o que vivem.', TRUE),
(14, 'Basico', 'c) amam aqueles que as aceitam.', FALSE),
(14, 'Basico', 'd) são gentis quando respeitadas.', FALSE),
(14, 'Basico', 'e) ridicularizam quem as intimida.', FALSE),
(15, 'Basico', 'a) conscientizar sobre a necessidade de otimização do consumo.', TRUE),
(15, 'Basico', 'b) divulgar espaços publicitários de grande visibilidade.', FALSE),
(15, 'Basico', 'c) sensibilizar para a conservação do patrimônio público.', FALSE),
(15, 'Basico', 'd) apresentar uma forma mais econômica de fazer publicidade.', FALSE),
(15, 'Basico', 'e) denunciar possíveis danos decorrentes de atos de vandalismo.', FALSE);

-- Nível Intermediário
INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Intermediario', 1, '(Enem PPL 2014)', NULL, 'Implementar políticas adequadas de alimentação e nutrição é uma meta prioritária em vários países do mundo. A partir da campanha If you can t read it, why eat it?, os leitores são alertados para o perigo de:', 'https://pt-static.z-dn.net/files/dcc/225cbb6ae4390ccd53439b5c52105b2b.png'),
('Intermediario', 2, '(Enem 2014)', 'Tennessee Mountain Properties: Description- Own a renovated house for less than $290 per month!!!!!!!! New windows, siding, flooring (laminate throughout and tile in entry way and bathroom), kitchen cabinets, counter top, back door, fresh paint and laundry on main floor. Heat bills are very low due to a good solid house and an energy efficient furnace. Disponível em: www.freerealestaeads.net. Acesso em: 30 nov. 2011 (adaptado).', 'Em jornais, há diversos anúncios que servem aos leitores. O conteúdo do anúncio veiculado por este texto interessará a alguém que esteja procurando:', NULL),
('Intermediario', 3, '(Brasil Escola)', NULL, 'Qual das alternativas apresenta apenas advérbios de tempo?', NULL),
('Intermediario', 4, '(UNIP)', NULL, 'It s ________ honor to meet ________ young lady from Sweden.', NULL),
('Intermediario', 5, '(Enem PPL 2013)', NULL, 'Tirinhas são construídas a partir de contextos sociais e podem promover reflexões diversas. Essa tirinha provoca no leitor uma reflexão acerca da:', 'https://media.brainly.com.br/image/rs:fill/w:1920/q:75/plain/https://pt-static.z-dn.net/files/dc9/bfec51a193c0c9c0e130c59360ba45ab.png'),
('Intermediario', 6, '(Enem PPL 2011)', NULL, 'Ao estabelecer uma relação entre a Matemática e o blues a partir da opinião pessoal de um dos rapazes, a charge sugere que:', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS8-Y2R6QlDkiyev8W2kFRQSqSQPPUuOCgzNz5lcnB_HTofWdtk'),
('Intermediario', 7, '(Enem 2014)', 'The Road Not Taken (by Robert Frost): Two roads diverged in a wood, and I — I took the one less traveled by, And that has made all the difference. Disponível em: www.poetryfoundation.org. Acesso em: 29 nov. 2011 (fragmento).', 'Estes são os versos finais do famoso poema The Road Not Taken, do poeta americano Robert Frost. Levando-se em consideração que a vida é comumente metaforizada como uma viagem, esses versos indicam que o autor:', NULL),
('Intermediario', 8, '(Enem PPL 2010)', 'Crystal Ball: Come see your life in my crystal glass — Twenty-five cents is all you pay Let me look into your past — Here s what you had for lunch today: Tuna salad and mashed potatoes, Collard greens pea soup and apple juice, Chocolate milk and lemon mousse. You admit I ve got told it all? Well, I know it, I confess, Not by looking, in my ball, But just by looking at your dress. SILVERSTEIN, S. Falling up. New York: Harper Collins Publishers, 1996.', 'A curiosidade a respeito do futuro pode exercer um fascínio peculiar sobre algumas pessoas, a ponto de colocá-las em situações inusitadas. Na letra da música Crystal Ball, essa situação fica evidente quando é revelado à pessoa que ela:', NULL),
('Intermediario', 9, '(Unesp)', NULL, 'Indique a alternativa que expressa o mesmo significado de: When children watch TV, they encounter a wide range of places, people, and information.', NULL),
('Intermediario', 10, '(Enem, 2020)', 'Finally, Aisha finished with her customer and asked what colour Ifemelu wanted for her hair attachments. “Colour four.” “Not good colour,” Aisha said promptly. “That s what I use.” “It look dirty. You don t want colour one?” “Colour one it too black. It looks fake,” Ifemelu said, loosening her headwrap. “Sometimes I use colour two, but colour four is closest to my natural colour.” […] She touched Ifemelu s hair. “Why you don t have relaxer?” “I like my hair the way God made it.” “But how do you comb it? Hard to comb,” Aisha said. Ifemelu had brought her own comb. She gently combed her hair, dense, soft and tightly coiled, until it framed her head like a halo. “It s not hard to comb if you moisturize it properly,” she said, slipping into the coaxing tone of the proselytizer that she used whenever she was trying to convince other black women about the merits of wearing their hair natural. Aisha snorted; she clearly could not understand why anybody would choose to suffer through combing natural hair, plucked a little attachment from the pile on the table ad began deftly to twist. ADICHIE, C. Americanah: A novel. New York: Anchor Books, 2013.', 'A passagem do romance da escritora nigeriana traz um diálogo entre duas mulheres negras: a cabeleireira, Aisha, e a cliente, Ifemelu. O posicionamento da cliente é sustentado por argumentos que:', NULL),
('Intermediario', 11, '(Enem, 2020)', NULL, 'Os recursos usados nesse pôster de divulgação de uma campanha levam o leitor a refletir sobre a necessidade de:', 'https://www.notamaxima.com.br/upl/uploads/enem_2020_1_dia_indagacao_02.jpg'),
('Intermediario', 12, '(Enem em inglês, 2018)', 'Don t write in English, they said, English is not your mother tongue… …The language I speak Becomes mine, its distortions, its queerness All mine, mine alone, it is half English, half Indian, funny perhaps, but it is honest, It is as human as I am human… …It voices my joys, my longings my Hopes… (Kamala Das, 1965:10) GARGESH, R. South Asian Englishes. In: KACHRU, B.B.; KACHRU, Y.; NELSON, C.L. (Eds.). The Handbook of World English. Singapore: Blackwell, 2006', 'A poetisa Kamala Das, como muitos escritores indianos, escreve suas obras em inglês, apesar de essa não ser sua primeira língua. Nesses versos, ela:', NULL),
('Intermediario', 13, '(Enem/2018)', 'Is it your opinion, Winston, that the past has real existence?/ [...] O\Brien smiled faintly. \I will put it more precisely. Does the past exist concretely, in space? Is there somewhere or other a place, a world of solid objects, where the past is still happening?\ \No.\ \Then where does the past exist, if at all? \In records. It is written down.\ \In records. And — —?\ \In the mind. In human memories.\ \In memory. Very well, then. We, the Party, control all records, and we control all memories. Then we control the past, do we not?\ ORWELL. G, Nineteen Eighty-Four. New York: Signet Classics, 1977', 'O romance 1984 descreve os perigos de um Estado totalitário. A ideia evidenciada nessa passagem é que o controle do Estado se dá por meio do(a):', NULL),
('Intermediario', 14, '(Enem 2012)', NULL, 'Cartuns são produzidos com o intuito de satirizar comportamentos humanos e assim oportunizam a reflexão sobre nossos próprios comportamentos e atitudes. Nesse cartum, a linguagem utilizada pelos personagens em uma conversa em inglês evidencia a: 
DONAR. Disponível em: http://politicalgraffiti.wordpress.com. Acesso em: 17 ago. 2011.', 'https://rachacuca.com.br/media/vestibulator/attachment/569-cartum-donar.png'),
('Intermediario', 15, '(Enem/2018)', 'Lava Mae: Creating Showers on Wheels for the Homeless- San Francisco, according to recent city numbers, has 4,300 people living on the streets. Among the many problems the homeless face is little or no access to showers. San Francisco only has about 16 to 20 shower stalls to accommodate them. But Doniece Sandoval has made it her mission to change that. The 51-year-old former marketing executive started Lava Mae, a sort of showers on wheels, a new project that aims to turn decommissioned city buses into shower stations for the homeless. Each bus will have two shower stations and Sandoval expects that they\ll be able to provide 2,000 showers a week. ANDREANO, C. Dísponível em: abcnews.go.com. Acesso: 26 jun. 2015 (adaptado).', 'A relação dos vocábulos shower, bus e homeless, no texto, refere-se a:', NULL);

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Intermediario', 'a) acessarem informações equivocadas sobre a formulação química de alimentos empacotados.', FALSE),
(1, 'Intermediario', 'b) consumirem alimentos industrializados sem o interesse em conhecer a sua composição.', TRUE),
(1, 'Intermediario', 'c) desenvolverem problemas de saúde pela falta de conhecimento a respeito do teor dos alimentos.', FALSE),
(1, 'Intermediario', 'd) incentivarem crianças a ingerirem grande quantidade de alimentos processados e com conservantes.', FALSE),
(1, 'Intermediario', 'e) ignorarem o aumento constante da obesidade causada pela má alimentação na fase de desenvolvimento da crianças.', FALSE),
(2, 'Intermediario', 'a) emprego no setor imobiliário.', FALSE),
(2, 'Intermediario', 'b) imóvel residencial para compra.', TRUE),
(2, 'Intermediario', 'c) serviço de reparos em domicílio.', FALSE),
(2, 'Intermediario', 'd) pessoa para trabalho doméstico.', FALSE),
(2, 'Intermediario', 'e) curso de decorador de interiores.', FALSE),
(3, 'Intermediario', 'a) already, always, then, above.', FALSE),
(3, 'Intermediario', 'b) first, here, rarely, yet.', FALSE),
(3, 'Intermediario', 'c) below, before, never, hard.', FALSE),
(3, 'Intermediario', 'd) first, already, usually, yet.', FALSE),
(3, 'Intermediario', 'e) lately, still, next, finaly.', TRUE),
(4, 'Intermediario', 'a) a / an.', FALSE),
(4, 'Intermediario', 'b) an / an.', FALSE),
(4, 'Intermediario', 'c) a / a.', FALSE),
(4, 'Intermediario', 'd) an / a.', TRUE),
(5, 'Intermediario', 'a) divisão de espaço com os pais.', FALSE),
(5, 'Intermediario', 'b) perda da atenção dos pais.', FALSE),
(5, 'Intermediario', 'c) semelhança com os pais.', TRUE),
(5, 'Intermediario', 'd) ausência dos pais.', FALSE),
(5, 'Intermediario', 'e) submissão aos pais.', FALSE),
(6, 'Intermediario', 'a) o blues, com seu ritmo depressivo, alivia o sentimento causado pela Matemática.', TRUE),
(6, 'Intermediario', 'b) as canções iniciadas com a contagem de 1 a 4 fazem lembrar o blues.', FALSE),
(6, 'Intermediario', 'c) as canções devem se iniciar com a contagem de 1 a 4 para se tornarem tristes.', FALSE),
(6, 'Intermediario', 'd) o blues, assim como a Matemática, consegue despertar um sentimento inspirador.', FALSE),
(6, 'Intermediario', 'e) o sentimento despertado pela Matemática serve como motivação para o blues.', FALSE),
(7, 'Intermediario', 'a) festeja o fato de ter sido ousado na escolha que fez em sua vida.', TRUE),
(7, 'Intermediario', 'b) lamenta por ter sido um viajante que encontrou muitas bifurcações.', FALSE),
(7, 'Intermediario', 'c) viaja muito pouco e que essa escolha fez toda a diferença em sua vida.', FALSE),
(7, 'Intermediario', 'd) reconhece que as dificuldades em sua vida foram todas superadas.', FALSE),
(7, 'Intermediario', 'e) percorre várias estradas durante as diferentes fases de sua vida.', FALSE),
(8, 'Intermediario', 'a) recebeu uma boa notícia.', FALSE),
(8, 'Intermediario', 'b) ganhou um colar de pedras.', FALSE),
(8, 'Intermediario', 'c) se sujou durante o almoço.', TRUE),
(8, 'Intermediario', 'd) comprou vestidos novos.', FALSE),
(8, 'Intermediario', 'e) encontrou uma moeda.', FALSE),
(9, 'Intermediario', 'a) When children watch TV, a wide range of places, people, and information will be encounter.', FALSE),
(9, 'Intermediario', 'b) When children watch TV, a wide range of places, people, and information are encountered.', FALSE),
(9, 'Intermediario', 'c) When children watch TV, a wide range of places, people, and information is encountered.', TRUE),
(9, 'Intermediario', 'd) When TV was watched, a wide range of places, people, and information are encountered by children.', FALSE),
(9, 'Intermediario', 'e) A wide range of places, people, and information will be encountered when children watched TV.', FALSE),
(10, 'Intermediario', 'a) reforçam um padrão de beleza.', FALSE),
(10, 'Intermediario', 'b) retratam um conflito de gerações.', FALSE),
(10, 'Intermediario', 'c) revelam uma atitude de resistência.', TRUE),
(10, 'Intermediario', 'd) demonstram uma postura de imaturidade.', FALSE),
(10, 'Intermediario', 'e) evidenciam uma mudança de comportamento.', FALSE),
(11, 'Intermediario', 'a) criticar o tipo de tratamento dado à mulher.', TRUE),
(11, 'Intermediario', 'b) rever o desempenho da mulher no trabalho.', FALSE),
(11, 'Intermediario', 'c) questionar a sobrecarga de atribuições da mulher.', FALSE),
(11, 'Intermediario', 'd) analisar as pesquisas acerca dos direitos da mulher.', FALSE),
(11, 'Intermediario', 'e) censurar a mulher pelo uso de determinadas palavras.', FALSE),
(12, 'Intermediario', 'a) usa a língua inglesa como efeito humorístico.', FALSE),
(12, 'Intermediario', 'b) recorre a vozes de vários escritores ingleses.', FALSE),
(12, 'Intermediario', 'c) adverte sobre o uso distorcido da língua inglesa.', FALSE),
(12, 'Intermediario', 'd) demonstra consciência de sua identidade linguística.', TRUE),
(12, 'Intermediario', 'e) reconhece a incompreensão na sua maneira de falar inglês.', FALSE),
(13, 'Intermediario', 'a) boicote a ideais libertários.', FALSE),
(13, 'Intermediario', 'b) veto ao culto das tradições.', FALSE),
(13, 'Intermediario', 'c) poder sobre memórias e registros.', TRUE),
(13, 'Intermediario', 'd) censura a produções orais e escritas.', FALSE),
(13, 'Intermediario', 'e) manipulação de pensamentos individuais.', FALSE),
(14, 'Intermediario', 'a) predominância do uso da linguagem informal sobre a língua padrão.', FALSE),
(14, 'Intermediario', 'b) dificuldade de reconhecer a existência de diferentes usos da linguagem.', TRUE),
(14, 'Intermediario', 'c) aceitação dos regionalismos utilizados por pessoas de diferentes lugares.', FALSE),
(14, 'Intermediario', 'd) necessidade de estudo da língua inglesa por parte dos personagens.', FALSE),
(14, 'Intermediario', 'e) facilidade de compreensão entre falantes com sotaques distintos.', FALSE),
(15, 'Intermediario', 'a) empregar moradores de rua em lava a jatos para ônibus.', FALSE),
(15, 'Intermediario', 'b) comissionar sem-teto para dirigir os ônibus da cidade.', FALSE),
(15, 'Intermediario', 'c) exigir das autoridades que os ônibus municipais tenham banheiros.', FALSE),
(15, 'Intermediario', 'd) abrigar dois mil moradores de rua em ônibus que foram adaptados.', FALSE),
(15, 'Intermediario', 'e) criar acesso a banhos gratuitos para moradores de rua.', TRUE);

-- Nível Avançado
INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Avancado', 1, '(IBFC INEP 2012)', NULL, 'The alternative that brings the sentences with the same meaning of “My cousin recovered from his health problems because he has completely changed his lifestyle” is', NULL),
('Avancado', 2, '(ADM&TEC 2024)', 'Netflix is trying to prove to the world that it is all grown up:
Netflix is trying to persuade Wall Street that it is now all grown up. After squeezing out millions of additional subscribers via its password sharing crackdown and through the introduction of cheaper advertiser-supported plans, the streamer knows that its growth spurts are coming to an end — and now it wants investors to stop obsessing over those pesky membership numbers and instead focus on other metrics.
"In our early days, when we had little revenue or profit, membership growth was a strong indicator of our future potential. But now we are generating very substantial profit and free cash flow. We are also developing new revenue streams like advertising and our extra member feature, so memberships are just one component of our growth", Netflix told shareholders as it reported quarterly earnings.
To that end, Netflix said that it will no longer report quarterly subscriber numbers, starting in 2025. Alas, the metric that Wall Street has forever judged Netflix on the metric that prompted legacy media companies to burn endless piles of cash in their bids to compete with the streamer — will be retired. The decision to shut off transparency on the metric represents a significant turning point in the streaming revolution. For years, Netflix has prided itself on being extraordinarily transparent. Now it is aiming to hold its cards closer to its chest. And given that streaming giant is the trendsetter in the space, one could expect that other media companies will be inspired by the company s move and also opt to cease reporting such data.
To be fair, what Netflix is saying is not necessarily off base either. As the company shifts its business model away from subscriptions and toward advertising and other revenue streams, it makes sense to consider how much time users are spending on the service. The more content a user consumes on Netflix, the more likely they are to continue paying for the service, and the more money Netflix then makes from that single subscriber. "We are focused on revenue and operating margin as our primary financial metrics — and engagement (i.e. time spent) as our best proxy for customer satisfaction,” Netflix underscored in its letter to shareholders.
Regardless, less transparency in an already opaque industry is not ideal. The walled garden of streaming already lacks the same detailed viewership data that Nielsen collects on linear television broadcasters. Now, visibility into the streaming world will get even dimmer.
The announcement from Netflix managed to overshadow its otherwise stellar quarter. The company handily beat expectations and added a staggering 9.3 million subscribers, meaning it now boasts nearly 270 million in total. Netflix also beat analyst expectations on both earnings and revenue. However, it was not all good news. Netflix forecasted its subscriber growth to be lower in quarter two, chalking it up to “typical seasonality.” That led the stock to slide nearly 5% in after-hours trading.
Whether "typical seasonality” is solely to blame, or whether the streamer is simply starting to hit a ceiling, is hard to tell. Perhaps it is a mix of both. Whatever the cause, the stock sliding on the less-than-ideal outlook is a prime example of why Netflix wants Wall Street to stop focusing on its subscriber numbers. And, in one year s time, investors won t have a choice.
', 'Based on Text |, mark the statements below as True (T) or False (F). ( ) ( ) Netflix s steps might lead other streaming companies to crack on reporting quarterly subscriber numbers.
( ) Excluding engagement, being less transparent is the key for Netflix to maintain its customer satisfaction.
( ) Netflix wants investors to stop obsessing over membership numbers and instead focus on other metrics.
( ) Falling short of expectations, the streaming company added a staggering 9.3 million subscribers.', NULL),
('Avancado', 3, '(CONTEMAX 2024)', 'Lisa is discussing instructions from her supervisor with a colleague. Convert the direct speech into reported speech. and choose the correct sentence. Supervisor: "You must prepare the lesson plans for next week." Lisa reported : "_____________________________"', NULL, NULL),
('Avancado', 4, '(FUVEST 2023)', 'We have been given no shortage of digital tools that should, in theory, help us work better, with more focus and efficiency, and connect us more easily with our colleagues. Instead, email, instant messaging, remote-meeting apps, work-flow and project-management software can feel like buckets with holes in the bottom, maddeningly inadequate to the task of keeping us from drowning in work. It is clear that something in the great digital-workplace experiment has gone wrong. Or maybe it is more accurate to say that it is still too early to expect that we would have figured out how to make things go right. "We are working now with new technologies that only emerged in the "90s," says Cal Newport, a Georgetown computer-science professor. "The idea that we immediately figured out the best way to use them is ahistorical. Of course we have not gotten it right yet."', 'The expression sublinhada no trecho "The idea that we immediately figured out the best way to use them is ahistorical" pode ser substituída, sem prejuízo do sentido, por', NULL),
('Avancado', 5, '(FUNDATEC 2024)', 'In the image below we can see a boy talking to the “Google Home Mini”, which is an electronic device, and then with a tiger:', 'Which of the alternatives below correctly fills out the gaps in the dialogue, from top to bottom?', 'https://i.pinimg.com/originals/ea/16/9f/ea169f227323170a1f7f037b194d1b1c.jpg'),
('Avancado', 6, '(PUC - SP 2017)', NULL, 'O candidato não conseguiu colocar a foto no passaporte porque :', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_5b85b68d2f8153e441e0c5fbfd6fbda0_294928.jpg.jpeg'),
('Avancado', 7, '(PUC - SP 2017)', NULL, 'O infográfico tem como objetivo principal:', 'https://qcon-assets-production.s3.amazonaws.com/images/provas/74936/222.png'),
('Avancado', 8, '(UERJ 2015)', NULL, 'And I should know. (panel 4) Modal verbs can be used to refer to a speaker s attitude. The modal should indicates that Calvin believes his knowledge of the bad quality of the TV show would be characterized as:', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQXsJ6OxMOJFS8PpGYE97jYZCmqepfwyBIjmxoL370qNFPKUM5a'),
('Avancado', 9, '(VUNESP - 2014)', 'The Institute for Supply Management s (ISM) manufacturing index rose to 53.2 from 51.3 in January. A reading above 50 indicates expansion. Separate data showed construction spending rose slightly in January, helped by residential construction. Manufacturing and construction are key to the US economy and there were fears that severe weather across many parts of the US may have hurt the sectors. Bradley Holcomb, chair of ISM s survey committee, said that while several manufacturers said severe weather was impacting their business, “other comments reflect optimism in terms of demand and growth in the near term”. Meanwhile, data released by the US Department of Commerce, showed that construction spending rose 0.1% in January, from December. Compared to the same month last year, construction spending was up 9.3%. However, the bad weather conditions impacted car sales in February with General Motors, Toyota and Ford all posting declines in their deliveries. But the drop in sales was less than expected and manufacturers were upbeat about the prospects in the coming months. “February auto sales emerged from a chill in the second half of the month, positioning the industry for a strong March,” said Bill Fay, general manager at Toyota, which saw a fall in deliveries of 4% during the month. General Motors sales fell 1%, compared to analysts forecast of a 6% drop. Chrysler and Nissan Motors beat the trend with sales increases of 11% and 16% respectively. Analysts said that overall car sales during the month had been helped by incentives and discounts offered by dealers to lure customers to showrooms in an attempt to cushion the impact of the severe weather conditions. However, as weather conditions improve, the discounts will reduce.', 'The third paragraph shows that', NULL),
('Avancado', 10, '(PUC Campinas - 2016)', 'Leia o texto para responder à questão. The colors of the rainbow so pretty in the sky Are also on the faces of people passing .. I... I see friends ..II.. hands Saying, "how do you do?" They are really saying, I love you.', 'The word that correctly fills the blank ..II.. is', NULL),
('Avancado', 11, '(Instituto Access - 2024)', NULL, 'Choose the correct option to complete the sentence: "Sadly, many people __________ serious illnesses due to lack of early detection."', NULL),
('Avancado', 12, '(Instituto Access - 2024)', 'On Friday, a major tech failure disrupted services worldwide and highlighted the vulnerability of interconnected technologies. Cybersecurity firm CrowdStrike apologized after an update to its antivirus software, which protects Microsoft Windows devices from attacks, caused a global outage. This led to thousands of flight cancellations and delays and affected banking, healthcare, and payment systems. Although the software bug has been fixed, experts warn that manually rebooting each affected computer will take significant time and effort. Microsoft estimated that 8.5 million computers globally were impacted by the glitch, making it the worst cyber event in history. The UK s National Cyber Security Centre and Germany s IT security agency have warned that scammers might exploit the situation. Despite the fix, it will take time to resolve all issues and clear backlogs. It is important to be prepared for such disruptions in the future and have resilient systems.', 'Read and mark the option which fills in the blanks accordingly.', NULL),
('Avancado', 13, '(Instituto Access - 2024)', NULL, 'Analise as sentenças e selecione a opção que apresenta a conjugação INCORRETA do tempo verbal perfeito.', NULL),
('Avancado', 14, '(VUNESP - 2013)', 'A transformer has a primary winding circuit with 200 turns and a secondary winding circuit with 10 turns. In an ideal, lossless, transformer model, the magnetic core permeability is infinite despite the voltages applied to the windings, the two windings are perfectly coupled and there are no internal resistance in the conductors. In such transformer, when a sinusoidal voltage is applied at the secondary winding with an amplitude of 5,0 [V] RMS, the RMS voltage in the primary winding terminals is equal to 100,0 [V].', 'Com relação a esse texto, assinale a alternativa correta.', NULL),
('Avancado', 15, '(VUNESP - 2023)', 'Leia o texto para responder a questão. Learning strategies are defined as “specific actions, behaviors, steps, or techniques—such as seeking out conversation partners, or giving one self-encouragement to tackle a difficult language task—used by students to enhance their own learning. When the learner consciously chooses strategies that suit his or her learning style and the L2 task at hand, these strategies become a useful toolkit for active, conscious, and purposeful self-regulation of learning. Learning strategies can be classified into six types; the compensatory strategies, for example, are those that help the learner make up for missing knowledge. A given strategy is neither good nor bad; it is neutral until the context of its use is thoroughly considered. What makes a strategy positive and helpful for a given learner? A strategy is useful if the following conditions are present: (a) the strategy relates to the L2 task at hand; (b) the strategy fits the particular student s learning style preferences to one degree or another; and (c) the student employs the strategy effectively and links it with other relevant strategies. Strategies that fulfill these conditions “make learning easier, faster, more enjoyable, more self-directed, more effective, and more transferable to new situations” (Oxford 1990, p. 8). Learning strategies can also enable students to become more independent and lifelong learners.', 'In a reading class, the text is about “World Cup host countries in the 21st century”. Aware of the fact that “a strategy is useful if it relates to the L2 task at hand”, the teacher coherently offers the following instruction to develop learners ability to scan texts in English:', NULL);


INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Avancado', 'If my cousin did not have change his lifestyle completely, he would not recover from his health problems.', FALSE),
(1, 'Avancado', 'If my cousin has not completely changed his lifestyle, he could not have recovered from his health problems.', FALSE),
(1, 'Avancado', 'If my cousin has not completely changed his lifestyle, he would not have recovered from his health problems.', FALSE),
(1, 'Avancado', 'If my cousin had not completely changed his lifestyle, he would not have recovered from his health problems.', TRUE),
(1, 'Avancado', 'If my cousin had not completely changed his lifestyle, he would not recovered from his health problems.', FALSE),
(2, 'Avancado', 'F. T. F. T.', FALSE),
(2, 'Avancado', 'F. F. T. F.', TRUE),
(2, 'Avancado', 'T. F. T. F.', FALSE),
(2, 'Avancado', 'T. T. F. T.', FALSE),
(3, 'Avancado', 'My supervisor said that we could prepare the lesson plans for next week.', FALSE),
(3, 'Avancado', 'My supervisor said that we had to prepare the lesson plans for next week.', TRUE),
(3, 'Avancado', 'My supervisor said that we must to prepare the lesson plans for next week.', FALSE),
(3, 'Avancado', 'My supervisor said that we has to prepare the lesson plans for next week.', FALSE),
(3, 'Avancado', 'My supervisor said that we might prepare the lesson plans for next week.', FALSE),
(4, 'Avancado', 'disturbed', FALSE),
(4, 'Avancado', 'constructed', FALSE),
(4, 'Avancado', 'failed', FALSE),
(4, 'Avancado', 'made', FALSE),
(4, 'Avancado', 'understood', TRUE),
(5, 'Avancado', 'to – no preposition – towards – to', FALSE),
(5, 'Avancado', 'to – on – to – of', TRUE),
(5, 'Avancado', 'no preposition – to – with – of', FALSE),
(5, 'Avancado', 'to – no preposition – with – of', FALSE),
(5, 'Avancado', 'no preposition – onto – with – to', FALSE),
(6, 'Avancado', 'Exceeded the number of attempts that the machine allowed.', FALSE),
(6, 'Avancado', 'Possibly did not have their ethnic-racial characteristics recognized by the program.', TRUE),
(6, 'Avancado', 'Did not observe the technical criteria necessary to complete the procedure.', FALSE),
(6, 'Avancado', 'Ignored the need to go through the items listed in the security aspects before making the next attempt.', FALSE),
(7, 'Avancado', 'Give examples of types of electronic bullying so that parents can protect themselves.', FALSE),
(7, 'Avancado', 'Show the bullied adolescent that they are not alone.', FALSE),
(7, 'Avancado', 'Draw the populatio s attention to the fact that bullying is a dangerous reality.', FALSE),
(7, 'Avancado', 'Show the population that combating bullying depends on each person s individual action.', TRUE),
(8, 'Avancado', 'Desirable.', TRUE),
(8, 'Avancado', 'Probable.', FALSE),
(8, 'Avancado', 'Surprising.', FALSE),
(8, 'Avancado', 'Mandatory.', FALSE),
(9, 'Avancado', 'Auto manufacturers were already expecting a drop in sales for February.', TRUE),
(9, 'Avancado', 'GM, Ford, and Toyota expected to sell more cars in February because of the winter.', FALSE),
(9, 'Avancado', 'Car sales are expected to drop in the months after February when the winter finishes.', FALSE),
(9, 'Avancado', 'Chrysler sold more cars than Toyota in February, but Nissan sold more than them all.', FALSE),
(9, 'Avancado', 'General Motors sold 6% fewer cars than Toyota in February.', FALSE),
(10, 'Avancado', 'Waving.', FALSE),
(10, 'Avancado', 'Shaking.', TRUE),
(10, 'Avancado', 'Grabbing.', FALSE),
(10, 'Avancado', 'Clapping.', FALSE),
(10, 'Avancado', 'Raising.', FALSE),
(11, 'Avancado', 'Die from.', TRUE),
(11, 'Avancado', 'Come down with.', FALSE),
(11, 'Avancado', 'Contract.', FALSE),
(11, 'Avancado', 'Are diagnosed with.', FALSE),
(12, 'Avancado', 'Restarted - blackout - installing - news - robbers.', FALSE),
(12, 'Avancado', 'Disrupted - outage - rebooting - glitch - scammers.', TRUE),
(12, 'Avancado', 'Installed - chaos - cleaning - fact - thieves.', FALSE),
(12, 'Avancado', 'Disturbed - news - reinstalling - story - programmers.', FALSE),
(12, 'Avancado', 'Destroyed - coup - sending - failure - criminals.', FALSE),
(13, 'Avancado', 'They had not eaten before the plane landed.', FALSE),
(13, 'Avancado', 'I will have finished my report by this time next week.', FALSE),
(13, 'Avancado', 'If you had studied for your exam, you would have passed.', FALSE),
(13, 'Avancado', 'He has written ten pages of the report.', FALSE),
(13, 'Avancado', 'They have are married for nearly fifty years.', TRUE),
(14, 'Avancado', 'In an ideal transformer, a non-sinusoidal voltage is applied to the secondary winding, with an amplitude of 5.0 RMS volts.', FALSE),
(14, 'Avancado', 'In an ideal transformer, a sinusoidal voltage is applied to the primary winding, with an amplitude of 5.0 RMS volts.', FALSE),
(14, 'Avancado', 'The ideal transformer, without losses, has infinite permeability, regardless of the intensity of the voltages applied to the windings, which are perfectly coupled without any internal resistance in their conductors.', TRUE),
(14, 'Avancado', 'The ideal transformer, without losses, has infinite permissiveness, which depends on the intensity of the voltages applied to the windings, which are perfectly coupled without any internal resistance in their conductors.', FALSE),
(14, 'Avancado', 'A transformer has a primary magnetic circuit with 200 turns and a secondary magnetic circuit with 10 turns.', FALSE),
(15, 'Avancado', 'Focus on the text s key ideas and ignore other elaborate details.', FALSE),
(15, 'Avancado', 'Carefully read the title and the first paragraph to anticipate the content of subsequent paragraphs.', FALSE),
(15, 'Avancado', 'Activate your prior knowledge to create a mental image about text content.', FALSE),
(15, 'Avancado', 'Compare the content of this text with texts you have read in Portuguese about the same theme.', FALSE),
(15, 'Avancado', 'Identify the countries which have held World Cup Championships in the last 22 years.', TRUE);

-- Nível Proficiente
INSERT INTO simulados (nivel, id_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Proficiente', 1, '(ENEM 2023-PPL)', NULL, 'MCPHAIL, W. Disponível em: https://fineartamerica.com. Acesso em: 25 out. 2021.Ao utilizar a expressão "be a shame if something were to happen to it", o pássaro:', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRzDUFxpgd1mORo5-8g3s2tIou1nOUbxJ0PooAp18eI4QR-M_se'),
('Proficiente', 2, '(ENEM 2023-EDITAL)', 'Things We Carry on the Sea We carry tears in our eyes: good-bye father, good-bye [mother We carry soil in small bags: may home never fade in our [hearts We carry carnage of mining, droughts, floods, genocides We carry dust of our families and neighbors incinerated [in mushroom clouds We carry our islands sinking under the sea We carry our hands, feet, bones, hearts and best minds [for a new life We carry diplomas: medicine, engineer, nurse, [education, math, poetry, even if they mean [nothing to the other shore We carry railroads, plantations, laundromats, [bodegas, taco trucks, farms, factories, nursing [homes, hospitals, schools, temples... built on [our ancestors backs We carry old homes along the spine, new dreams in our [chests We carry yesterday, today and tomorrow W are orphans of the wars forced upon us We are refugees of the sea rising from industrial wastes And we carry our mother tongues [... ] As we drift... in our rubber boats... from shore... to shore... [to shore... PING, W. Disponível em: https://poets.org. Acesso em: 1 jun. 2023 (fragmento).', 'Ao retratar a trajetória de refugiados, o poema recorre à imagem de viagem marítima para destacar o(a):', NULL),
('Proficiente', 3, '(FUVEST 2024)', 'Vincent van Gogh. Salvador Dalí. Frida Kahlo. Casual perusers of ads everywhere...', 'De acordo com o texto, muitos visitantes das exposições de arte imersivas demonstram:', NULL),
('Proficiente', 4, '(FUVEST 2024)', 'Over the last two decades, technology companies and policymakers...', 'Conforme o texto, um dos motivos para a disparidade relativa à prática de atividades físicas por alunos, segundo o nível de renda, reside:', NULL),
('Proficiente', 5, '(IME 2023)', 'The climate is changing — the thing is, it is not just due to humans: By Tonya T. Neaves Natural forces beyond human control are also gradually affecting our climate. These geophysical forces are vital to understanding global warming. Man is indeed responsible for a large portion — possibly even a majority — of global warming. But also in play are complex gravitational interactions, including changes in the Earth s orbit, axial tilt and torque. This fact needs to be included in the public debate. Because these gravitational shifts, occurring over millennia, can influence climate patterns and ultimately lead to noticeable variations in seasons. Interestingly, research suggests climate change can alter the tilt of the Earth, but an unrelated change in tilt can also further change the climate. It is a balance-counterbalance relationship. Changes in seasons can also affect other types of storms, including severe winter snowstorms and tornadoes. The variations in the Earth s orbit are known as the Milankovitch cycles — after the Serbian geophysicist Milutin Milankovic, who hypothesized this phenomenon in the 1920s. He discovered that variations in the Earth s path around the Sun, axial tilt and torque could together affect our climate. Even a slight change or orientation in the precession of the Earth s rotating body can cause a wobbling effect shifting torque in different areas since the planet is not a perfect sphere to some people s surprise. Now would seem a particularly apt time to act. The 2017 Atlantic hurricane season was an intense, record-setting period. With several landfall hurricanes barreling their way through the Caribbean and Gulf of Mexico, devastating parts of the Leeward Islands and United States. Still, even President Donald J. Trump has implied the whole of idea climate change may just be a hoax. Most Republicans seem to agree that it is not a serious problem. Meanwhile, while some Democrats have tried to use the frequency and intensity of storms in the hopes of highlighting the climate change conversation, even this effort has seemed muted. The heightened culture of disaster only feeds our attention on political banter and ideological semantics with no room for informed 20 decision-making. Though climate change is inevitable, we also need to have a healthy appreciation of the fact that climate shifts are not just limited to rapidly changing weather patterns. Turning the corner into unexplored territory is always difficult. By having a broader sense of communal resiliency — social, political and economic standing — we can manage this unavoidable pendulum of climate extremes. Adapted from: THINK - Opinion, Analysis, Essays in: https://www.nbcnews.com/think/opinion/climate-changingnot-just-because-humans-here-s-why-matters-ncna824271 [Accessed on March 10th, 2023].', 'Choose the wrong option according to the text:', NULL),
('Proficiente', 6, '(IME 2023)', 'Climate of conspiracy: A meta-analysis of the consequences of belief in conspiracy theories about climate change: By Mikey Biddlestone, Flavio Azevedo, Sander van der Linden Despite widespread scientific consensus on climate change, conspiracy theories about its causes and consequences are flourishing. In response, psychological research has started to investigate the consequences of espousing conspiracy beliefs about climate change. Although some scholars maintain that the evidence for a causal link between belief in conspiracy theories and behavior remains elusive, others have argued that climate change conspiracy theories undermine pro-climate action. Overall, we find clear evidence that climate conspiracy beliefs have moderate-to-large negative correlations with not only acceptance of (climate) science, trust, and pro-environmental concern, but also with behavioural intentions and policy support. Most of these effects were not moderated by design (experimental vs. correlational), political ideology, or prior conspiracy beliefs. After a meta-analysis we find clear evidence that climate change conspiracy beliefs correlate with a host of concerning societal outcomes, including lower acceptance of (climate) science, distrust, lower concern for the environment, and also lower intentions to take action and support pro-environmental policies. An important open question concerns the direction of causality. Although it is possible—and perhaps likely—that people who are skeptical of climate change are more likely to endorse conspiracy theories about global warming, we can also expect that people who are exposed to climate change conspiracy theories become more skeptical and are less likely to take pro-environmental action. In one of the included experiments, people were less likely to sign a petition to support climate change policies if they had been exposed to conspiracy content. This implies that the spread of climate change conspiracy theories could play a role in delaying or preventing important policy changes. Based on this review, we suggest that it is crucial to continue investigating how climate change conspiracy theories influence societal action, in order to understand better how they might delay the transition to a more sustainable future. Biddlestone, M., Azevedo, F., van der Linden, S. (2020).' , 'Acoording to the text, there is no correlation between climate conspiration theories and:', NULL),
('Proficiente', 7, '(ITA-2020-1ª FASE)', 'About seven years ago, three researchers at the University of Toronto built a system that could analyze thousands of photos and teach itself to recognize everyday objects, like dogs, cars and flowers. The system was so effective that Google bought the tiny start-up these researchers were only just getting off the ground. And soon, their system sparked a technological revolution. Suddenly, machines could see in a way that was not possible in the past. This made it easier for a smartphone app to search your personal photos and find the images you were looking for. It accelerated the progress of driverless cars and other robotics. And it improved the accuracy of facial recognition services, for social networks like Facebook and for the country s law enforcement agencies. But soon, researchers noticed that these facial recognition services were less accurate when used with women and people of color. Activists raised concerns over how companies were collecting the huge amounts of data needed to train these kinds of systems. Others worried these systems would eventually lead to mass surveillance or autonomous weapons.', 
'De acordo com as informações do texto, selecione a alternativa que melhor complete a afirmação: The new system proved to be less precise when:', NULL),
('Proficiente', 8, '(ITA-2019-1ª FASE)', NULL, 'No último quadrinho, o chefe do jornalista: Fonte: http://www.commitstrip.com/en/2015/10/26/journalists-today/? Acesso em maio de 2018.', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT29rCl8ikCQo7KTz5neuMm1_xsHk7xJnby3_SBH8Vztf8i2Wiq'),
('Proficiente', 9, '(ITA-2024)',  'Read Your Way Through Salvador: By Itamar Vieira Junior and translated by Johnny Lorenz. July 19, 2023. I was born in Salvador, in the Brazilian state of Bahia, and lived in the general vicinity until I reached the age of 15. But it was when I left that I really came to know my city. How was I able to discover more about my birthplace while traveling far from home? It might sound rather clichéd but, I assure you, literature made this possible: It took me on a journey, long and profound, back home, enveloping me in words and imagination. To understand the formation of our unique society and, consequently, the cityscape of Salvador, one should read, before anything else, The Story of Rufino: Slavery, Freedom and Islam in the Black Atlantic, by João José Reis, Flávio dos Santos Gomes and Marcus J.M. de Carvalho. Rufino was an alufá, or Muslim spiritual leader, born in the Oyo empire in present-day Nigeria and enslaved during his adolescence. The Story of Rufino is an epic tale, encapsulating the life of one man in search of freedom as well as the history of the development of Salvador itself, a place inextricably linked with the diaspora across the Black Atlantic. Another book for which I have deep affection is The City of Women, by the American anthropologist Ruth Landes. It offers an intriguing perspective, focusing on matriarchal power in candomblé, an Afro-Brazilian sacred practice, and revealing how the social organization of its spiritual communities reverberates across the city. If you want to feel the intensity of life on the streets of Salvador, these two books, both by Amado, are indispensable: Captains of the Sands and Dona Flor and Her Two Husbands. The first is a coming-of-age story in which we follow a group of children and adolescents living on the streets and on the beaches around the Bay of All Saints. Written more than 80 years ago, the book was banned and even burned in the public square during the dictatorship of Getúlio Vargas in the first half of the 20th century. As a portrait of Salvador, it is still relevant and reveals our deep inequalities. Dona Flor and her Two Husbands is one of Amado s most popular novels, translated into more than 30 languages and adapted many times for theater, cinema, and television. The book is a kind of manifesto for a woman s liberation. Dona Flor possesses great culinary talent, and oppressed by a patriarchal society, finds herself divided between two men, one being her deceased husband. While the novel captures the daily life of the city in the 1940s, it is also a wonderful guide to the cuisine of Salvador, with its African and Portuguese influences. I invite readers to travel into the interior of Bahia, many hours by car from Salvador to the region known as the Sertão, whose name translates loosely to backwoods. Two books can also transport you there, and they are sides of the same story: Backlands: The Canudos Campaign,  by Euclides da Cunha, and The War of the End of the World, by Mario Vargas Llosa. Backlands is one of the most important works in the history of Brazilian literature. It is a journalistic telling that introduces us not only to the brutal War of Canudos, but also to the intriguing landscape of the Sertão, a place so full of contradictions. In his writing of the conflict, da Cunha tells the story of the genesis of the tough sertanejo: a mythic, cowboyesque figure of the drought-stricken, lawless interior. The War of the End of the World is an essential epic that amplifies the narrative of Backlands, bringing a more imaginative, creative aspect to the story of Antônio Conselheiro, the spiritual leader of a rebellion, and of the multitude that followed him to their deaths.',
'According to the text, the author recommends the book The Story of Rufino: Slavery, Freedom and Islam in the Black Atlantic for the reader to:', NULL),
('Proficiente', 10, '(UFPR-2022-1ª FASE)', 'The surprising history of India s vibrant sari tradition: South Asian women have draped themselves in colorful silks and cottons for eons. The ways they are made and worn are dazzling and diverse. The word “sari” means “strip of cloth” in Sanskrit. But for the Indian women – and a few men – who have been wrapping themselves in silk, cotton, or linen for millennia, these swaths of fabric are more than just simple garments. They are symbols of national pride, ambassadors for traditional (and cutting-edge) design and craftsmanship, and a prime example of the rich differences in India s 29 states. “The sari both as symbol and reality has filled the imagination of the subcontinent, with its appeal and its ability to conceal and reveal the personality of the person wearing it,” says Delhi-based textile historian Rta Kapur Chishti, author of Saris of India: Tradition and Beyond and co-founder of Taanbaan, a fabric company devoted to reviving and preserving traditional Indian spinning and weaving methods. The first mention of saris (alternately spelled sarees) is in the Rig Veda, a Hindu book of hymns dating to 3,000 B.C.; draped garments show up on Indian sculptures from the first through sixth centuries, too. What Delhi-based textile historian Rta Kapur Chishti calls the “magical unstitched garment” is ideally suited to India s blazingly hot climate and the modest-dress customs of both Hindu and Muslim communities. Saris also remain traditional for women in other South Asian countries including Pakistan, Bangladesh, and Nepal. Available in: https://www.nationalgeographic.com/travel/photography/the-story-of-the-sari-in-india/.', 
'In the first sentence of the text, the underlined and in bold type word “eons” means:', NULL),
('Proficiente', 11, '(UFPR-2017-1ª FASE)', 'Britain will ban sales of new gasoline and diesel cars starting in 2040 as part of a bid to clean up the country s air. The decision to phase out the internal combustion engine heralds a new era of low-emission technologies with major implications for the auto industry, society and the environment. “We can t carry on with diesel and petrol cars”, U.K. environment secretary Michael Gove told the BBC on Wednesday. “There is no alternative to embracing new technology”. Almost 2.7 million new cars were registered in the U.K. in 2016, making it the second biggest market in Europe after Germany. Meeting the 2040 deadline will be a heavy lift. British demand for electric and fuel cell cars, as well as plug-in hybrids, grew 40% in 2015, but they only accounted for less than 3% of the market. Still, experts say sales of clean cars are likely to continue on their dramatic upward trajectory. The car industry says that demand for electric vehicles will only reach a tipping point once they are cheaper to own than conventional vehicles. The deadline was announced by the government on Wednesday as part of a plan to reduce air pollution. The blueprint highlighted roughly £1.4 billion in government investment designed to help ensure that every vehicle on the road in Britain produces zero emissions by 2050. Gove said action was needed because gasoline and diesel engines contribute to health problems, “accelerate climate change, do damage to the planet and the next generation”. Roughly 40,000 deaths in Britain each year are attributable to outdoor air pollution, according to a study published last year by the Royal College of Physicians. Dirty air has been linked to cancer, asthma, stroke and heart disease, among other health issues. The problem is especially pronounced in big cities. London surpassed the European Union s annual limit for nitrogen dioxide exposure just five days into the new year, according to King s College. The university estimates that air pollution is responsible for 9,400 premature deaths in the city every year. The timeline for ending sales of internal combustion engines mirrors one proposed in early July by France. President Emmanuel Macron has given the auto industry the same deadline to make the switch to cleaner tech. “We are quite rightly in a position of global leadership when it comes to shaping new technology”, Gove said. But the auto industry, which supports over 800,000 jobs in the U.K., is wary of hard deadlines. Other countries have been even more ambitious than the U.K. India is planning to stop selling gas-powered vehicles by 2030. The German car industry and government officials will meet in early August to discuss the future of diesel engine technology. Manufacturers are trying to avoid diesel cars being banned from German towns and cities. Available: http://money.cnn.com/2017/07/26/news/uk-bans-gasoline-diesel-engines-2040/index.html. Adapted. Accessed: July 26, 2017.', 
'Consider the following excerpt taken from the text: British demand for electric and fuel cell cars, as well as plug-in hybrids, grew 40% in 2015, but they only accounted for less than 3% of the market. Choose the alternative that conveys the same meaning of the excerpt above.', NULL),
('Proficiente', 12, '(FUVEST-2009-1ª FASE)', 'Two in every three people on the planet–some 4 billion in total–are “excluded from the rule of law.” In many cases, this begins with the lack of official recognition of their birth: around 40% of the developing world s five-year old children are not registered as even existing. Later, people will find that the home they live in, the land they farm, or the business that they start, is not protected by legally enforceable property rights. Even in the rare cases when they can afford to go to court, the service is poor. India, for example, has only 11 judges for every 1 million people. These alarming statistics are contained in a report from a commission on the legal empowerment of the poor, released on June 3rd at the United Nations. It argues that not only are such statistics evidence of grave injustice, they also reflect one of the main reasons why so much of humanity remains mired in poverty. Because they are outside the rule of law, the vast majority of poor people are obliged to work (if they work at all) in the informal economy, which is less productive than the formal, legal part of the economy. The Economist, June 7th 2008.', 
'O relatório citado no texto observa que:', NULL),
('Proficiente', 13, '(ITA-2015-1ª FASE)', NULL, 'A reportagem anunciada na tirinha:', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSmao16x_i7XtkGh_k-uWjkTsq77N8BrnWjbs0LV9lwc-xBGst0'),
('Proficiente', 14, '(ITA-2014-1ª FASE)',  NULL, 'Em “the more I learn, the less clear anything gets”, mantém-se o mesmo sentido em:', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_a29b481a0765e5f4327c9b6e857fd251_187580.jpg.jpeg'),
('Proficiente', 15, '(IME-2021/2022-2ª FASE)', 'Chariot-  Rodrigo Quijada Plubins- Definition
The chariot was a light vehicle, usually on two wheels, drawn by one or more horses, often carrying two standing persons, a driver and a fighter using bow-and-arrow or javelins. The chariot was the supreme military weapon in Eurasia roughly from 1700 BCE to 500 BCE but was also used for hunting purposes and in sporting contests such as the Olympic Games and in the Roman Circus Maximus.
Horses were not used for transport, ploughing, warfare or any other practical human activity until quite late in history, and the chariot was the first such application. Donkeys and other animals were preferred in early civilizations.
The Horse- The horse s main ecological niche was the Eurasian steppe; a very wide (4,800 km) and narrow (800 km on average) strip of grassland running roughly from Hungary to China, encompassing parts of what today is Ukrania, southern Russia, Kazakhstan, Uzbekistan, Turkmenistan, Kyrgyzstan, Tajikistan and Mongolia. For most of ancient history, the steppe - which means “wasteland” in Russian - was the home of nomadic societies whose economy was based on herding, complemented by hunting and, to a much lesser degree, sporadic, itinerant agriculture. No cities or settled communities existed in the steppe, save a very few spots.
Steppe dwellers domesticated the horse for the purpose of breeding it for food like sheep and other animals already domesticated. That process is unfortunately poorly understood, and it occurred sometime before 2500 BCE. The wheel, an invention imported from the Middle East, had arrived in the steppe around 3100 BCE. The invention of the chariot in the steppe - perhaps originally meant as an improved tool for hunting - occurred roughly by 2000 BCE, probably in the area just east of the southern Ural mountains, where the oldest chariots have been unearthed. The word for horse appears just around this date for the first time in Mesopotamia, when an increase in north-south trade through Iran is attested.
Invention of the Chariot- The chariot then became a moving platform from which soldiers could shoot at enemies. Arrows and javelins were the main weapons used by the fighter on board, while a second person drove the chariot. The tactic was to move constantly, in and out of the battle, shooting from a distance.
There is no clear explanation as to why humans invented the chariot first, before riding the horse directly, which seems more straightforward to us. A chariot was obviously more expensive than the horse alone, and chariots could not enter or properly manoeuver in landscapes where a mounted horse can, such as hills, marshes or forests. We know people tried mounting horses very early, as we have found drawings depicting it, but those seem rare experiments that did not seem to work. The most common scholarly suggestion is that horses at that time were weaker than in the present, unsuitable for supporting a man and only after a very long period of constant, selective breeding, did a stronger horse come into being. Horses started consistently to be mounted roughly a millennium and a half after the chariot was invented.
The “compound bow”, invented sometime during the second millennium BCE, was the final ingredient for the rise of a deadly ensemble. Bow and arrow were much older, and the innovation of the compound bow was the use of two types of materials, inside and outside the bow, which gave it considerably more power. Compound bows were able to accurately hit a target 300 m away, and penetrate an armour 100 m away. It was the preferred weapon of charioteers and later horseback riding societies. Its power is reflected in the fact that these bows were last used in war as recently as the 19th century CE by the Chinese, well into the age of firearms.
We have scarce knowledge of what happened with the communities in the steppe once the chariot was invented. We can assume that war intensified - and some evidence about it does exist -, and those who first or better grasped the new invention stormed their neighbours, sizing valuable hunting and pasturing land rights. We truly understand the impact of the chariot only when this new form of warfare came out of the steppes and into the settled, agricultural lands.
Charioteers & Warfare- The first reference to charioteers comes from Syria around 1800 BCE. Over the course of the next four centuries, chariots advanced into civilization, either by direct migration of steppe people or by diffusion, and it quickly came to be the preferred elite weapon.
(...) Everywhere, in Europe, the Middle East, India, and China, all rulers, from petty chiefs to great pharaohs, took the chariot as their master weapon. They started depicting themselves riding chariots, waging wars in chariots, including chariots and horses in their tombs as symbols of power, and so on. Their surrounding aristocracy, of course, followed suit, so the elite forces in every polity came to be charioteers. The horse came to be a valuable military asset, no longer a food source. Horse breeding became key for these states, and all powerful kings aspired to have the proper stables to supply their armies with chariots; imports from the steppes, though, long remained their major source.
The most famous chariot battle was that of Kadesh (1294 BCE), fought between the two superpowers of the time, Egypt and Hatti (Hittites), where some 50 chariots are presumed to have participated for each side. The small number of chariots compared to infantry troops is a good indicator of how effective the chariot was: in China, the ratio was up to 25 infantry soldiers per chariot.
Decline in Use- The use of the chariot declined very slowly, starting around 500 BCE (and yet, in some parts of Europe the technology was just arriving at that time). First and probably foremost, because horseback riding was developed in the steppes, and slowly but surely replaced the need for chariots. The first known forces mounting horses were those of the Scythians, steppe people who in the 7th century BCE attacked the Assyrian empire on horseback. Second, because infantry, formerly helpless against chariots, became more sophisticated due to the expanding use of iron weapons (from c. 1200 BCE onwards), and to new tactics in the form of phalanx formations. Fighting the invading Romans, the Celts were probably the last people who used chariots extensively, until around the 4th century CE.
Adapted from: Chariot. World History Encyclopedia. Available at: https://www.worldhistory.org/chariot/ [Accessed on 5th March 2021]. VOCABULARY: BCE – Before Common Era (or BC, Before Christ)/CE – Common Era (or AD, Anno Domini)', 'Choose the correct option', NULL);


INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Proficiente', 'Expresses an idea of a threat.', TRUE),
(1, 'Proficiente', 'Demonstrates a suggestion of food.', FALSE),
(1, 'Proficiente', 'Expresses a sense of shame.', FALSE),
(1, 'Proficiente', 'Reveals an event of the past.', FALSE),
(1, 'Proficiente', 'Portrays an attempt to get closer.', FALSE),
(2, 'Proficiente', 'Risk of cultural clashes.', FALSE),
(2, 'Proficiente', 'Impact of teaching history.', FALSE),
(2, 'Proficiente', 'Importance of environmental struggle.', FALSE),
(2, 'Proficiente', 'Existence of plural experiences.', TRUE),
(2, 'Proficiente', 'Need for professional qualification.', FALSE),
(3, 'Proficiente', 'Fascination with technological innovations used by curators.', FALSE),
(3, 'Proficiente', 'Discomfort caused by excessive sensory stimuli.', FALSE),
(3, 'Proficiente', 'Curiosity about the biography of painters and artistic movements.', FALSE),
(3, 'Proficiente', 'Appreciation of information provided by guides and educators.', FALSE),
(3, 'Proficiente', 'Indifference to art simulations.', TRUE),
(4, 'Proficiente', 'The persistent divide between the grades of rich and poor students.', FALSE),
(4, 'Proficiente', 'Cuts in spending and changes in priorities in some public schools.', TRUE),
(4, 'Proficiente', 'Preference for players with superior competition potential.', FALSE),
(4, 'Proficiente', 'Reduction of scholarships for adolescents from families below the poverty line.', FALSE),
(4, 'Proficiente', 'Holding tournaments funded by NGO donations.', FALSE),
(5, 'Proficiente', 'Politicians said that climate change may just be fake.', FALSE),
(5, 'Proficiente', 'Variations in the Earth s path might affect our climate.', FALSE),
(5, 'Proficiente', 'Human beings are the only responsible for global warming.', TRUE),
(5, 'Proficiente', 'Global Warming is affecting season changes.', FALSE),
(5, 'Proficiente', 'Changing the Earth s climate is inevitable.', FALSE),
(6, 'Proficiente', 'Disbelief in Science.', FALSE),
(6, 'Proficiente', 'Politicians.', FALSE),
(6, 'Proficiente', 'Depressed people.', TRUE),
(6, 'Proficiente', 'Skeptical people.', FALSE),
(6, 'Proficiente', 'Climate denials.', FALSE),
(7, 'Proficiente', 'Applied to driverless cars.', FALSE),
(7, 'Proficiente', 'Adjusted to users face recognition in social networks.', FALSE),
(7, 'Proficiente', 'Identifying inanimate objects like cars and plants.', FALSE),
(7, 'Proficiente', 'Used to identify Africans and African descendants.', TRUE),
(7, 'Proficiente', 'Tested by American law enforcement agencies.', FALSE),
(8, 'Proficiente', 'Solicita que ele lhe mostre as imagens que está escrevendo.', FALSE),
(8, 'Proficiente', 'Fica entusiasmado porque ele concorda que as imagens são sensacionalistas.', FALSE),
(8, 'Proficiente', 'Demonstra o interesse e pede que ele lhe mostre os dados do teste mencionado.', TRUE),
(8, 'Proficiente', 'Muda de ideia e demanda que ele exiba as ilustrações dos jornais concorrentes.', FALSE),
(8, 'Proficiente', 'Rende-se à lógica das redes sociais após checar a repercussão das fotos publicadas.', FALSE),
(9, 'Proficiente', 'Establish a connection of the book with Salvador, which epitomizes the Black diaspora.', TRUE),
(9, 'Proficiente', 'Understand how Rufino s Nigerian roots led him to fight for freedom in Salvador.', FALSE),
(9, 'Proficiente', 'Learn about Muslim leaders and their influence on cultures such as the present “quilombolas”.', FALSE),
(9, 'Proficiente', 'Find out how the city of Salvador presents a unique mix of African and European cultures.', FALSE),
(9, 'Proficiente', 'Agree that freedom of religion and belief is the most precious human right worth fighting for.', FALSE),
(10, 'Proficiente', 'The last few years.', FALSE),
(10, 'Proficiente', 'An extremely long period of time.', TRUE),
(10, 'Proficiente', 'Many years to come.', FALSE),
(10, 'Proficiente', 'Special occasions.', FALSE),
(10, 'Proficiente', 'Indian women.', FALSE),
(11, 'Proficiente', 'In 2015, British clean energy car manufacturers dominated the automobile market.', FALSE),
(11, 'Proficiente', 'The search for plug-in hybrid cars is not as large as for electric and fuel cell cars.', FALSE),
(11, 'Proficiente', '40% of the cars sold in Britain in 2015 use clean energy.', FALSE),
(11, 'Proficiente', 'Only 3% of the car sales in the market refer to petrol energy vehicles.', FALSE),
(11, 'Proficiente', 'In 2015, the majority of the cars sold in Britain were internal combustion energy vehicles.', TRUE),
(12, 'Proficiente', 'A ilegalidade é uma condição combatida em países subdesenvolvidos.', FALSE),
(12, 'Proficiente', 'Os dados estatísticos sobre a pobreza no mundo são incompletos.', TRUE),
(12, 'Proficiente', 'O fortalecimento do poder legal dos pobres melhoraria sua condição econômica e social.', FALSE),
(12, 'Proficiente', 'A pobreza só poderia ser combatida com a intervenção das Nações Unidas.', FALSE),
(12, 'Proficiente', 'A economia informal está em vias de ser abolida.', FALSE),
(13, 'Proficiente', 'Mostra a relação direta entre a obesidade e consumo de produtos calóricos.', FALSE),
(13, 'Proficiente', 'Divulga um estudo científico com o objetivo de mudar o comportamento da audiência.', FALSE),
(13, 'Proficiente', 'Demonstra indiferença com relação ao tema.', TRUE),
(13, 'Proficiente', 'Estimula o uso de redes sociais para divulgar produtos dos patrocinadores.', FALSE),
(13, 'Proficiente', 'Revela que 70% das pessoas com sobrepeso são sedentárias.', FALSE),
(14, 'Proficiente', 'More learning, less obscurity.', FALSE),
(14, 'Proficiente', 'More learning, more obscurity.', TRUE),
(14, 'Proficiente', 'Less learning, more obscurity.', FALSE),
(14, 'Proficiente', 'Less learning, less doubts.', FALSE),
(14, 'Proficiente', 'More doubts, more obscurity.', FALSE),
(15, 'Proficiente', 'In a battle, one soldier needed to aim at an enemy and another had to guarantee a long stationary position for the chariot.', FALSE),
(15, 'Proficiente', 'The main war tactic had to assure safety for the ones at the back of the main group of fighters.', FALSE),
(15, 'Proficiente', 'It is believed that riding a horse made people think of using a chariot for military purposes.', FALSE),
(15, 'Proficiente', 'Evidence shows why riding a horse increased the breeding of horses.', FALSE),
(15, 'Proficiente', 'If a person were riding a horse, a variety of military actions could be possible.', TRUE);



