CREATE DATABASE portal_ingles;

CREATE TYPE nivel_enum AS ENUM ('Basico', 'Intermediario', 'Avancado', 'Proeficiente');

CREATE TABLE simulados (
    id SERIAL PRIMARY KEY, 
    nivel nivel_enum NOT NULL,
    numero_pergunta INT NOT NULL CHECK (numero_pergunta BETWEEN 1 AND 15), 
    titulo VARCHAR(50) NOT NULL, 
    texto_pergunta TEXT,
    pergunta_texto TEXT, 
    url VARCHAR(255), 
    UNIQUE (nivel, numero_pergunta)
);
CREATE TABLE alternativas (
    id SERIAL PRIMARY KEY, 
    id_pergunta INT NOT NULL, 
    nivel nivel_enum NOT NULL,
    texto_alternativa TEXT NOT NULL, 
    correta BOOLEAN NOT NULL, 
    FOREIGN KEY (id_pergunta) REFERENCES simulados(id) ON DELETE CASCADE
);

-- Nível Básico

INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Basico', 1, '(Enem 2021)', NULL, 'A presença de at odds with na fala da personagem do cartum revela o(a):', 'https://blogger.googleusercontent.com/img/a/AVvXsEhCvRSIDqYEwlUR-cW3xR4EpXkw35jJeGURtAx8e4uvrtKEkBvhGIM13Be357bLKauia5nZqyvEoG6-nkT9W8dIbSmF6UIq_zG2SDzKclfJhtK3WilvF0QDtksY6qDgMH7Z-eTibyCaY5oRWwpL7tFwsE8miV0qhofs9rMicZkzCusC_1_Ym0zlEjoL=s600'),
('Basico', 2, '(Enem 2019)', 'A pet is certainly a great friend. After a difficult day, pet owners quite literally feel the love. In fact, for nearly 25 years, research has shown that living with pets provides certain health benefits. Pets help lower blood pressure and lessen anxiety. They boost our immunity. They can even help you get dates. Allergy Fighters A growing number of studies have suggested that kids growing up in a home with furred animals will have less risk of allergies and asthma. Date Magnets Dogs are great for making love connections. Forget Internet matchmaking – a dog is a natural conversation starter. Dogs for the Aged Walking a dog or just caring for a pet – for elderly people who are able – can provide exercise and companionship. Good for Mind and Soul Like any enjoyable activity, playing with a dog can elevate levels of serotonin and dopamine – nerve transmitters that are known to have pleasurable and calming properties. Good for the Heart Heart attack patients who have pets survive longer than those without, according to several studies.', 'Ao discutir sobre a influência de animais de estimação no bem-estar do ser humano, a autora, a fim de fortalecer seus argumentos, utiliza palavras e expressões como research, a growing number of research e several studies com o objetivo de:', NULL),
('Basico', 3, '(Enem 2016)', 'BOGOF is used as a noun as in There are some great bogofs on at the supermarket or an adjective, usually with a word such as offer or deal — there are some great bogof offers in store. When you combine the first letters of the words in a phrase or the name of an organisation, you have an acronym. Acronyms are spoken as a word so NATO (North Atlantic Treaty Organisation) is not pronounced N-A-T-O. We say NATO. Bogof, when said out loud, is quite comical for a native speaker, as it sounds like an insult, Bog off! meaning go away, leave me alone, slightly childish and a little old-fashioned. BOGOF is the best-known of the supermarket marketing strategies. The concept was first imported from the USA during the 1970s recession, when food prices were very high. It came back into fashion in the late 1990s, led by big supermarket chains trying to gain a competitive advantage over each other. Consumers were attracted by the idea that they could get something for nothing. Who could possibly say no?', 'Considerando-se as informações do texto, a expressão bogof é usada para:', NULL),
('Basico', 4, '(Enem 2022)', NULL, 'Na tirinha, o comportamento da mulher expressa:', 'https://kuadro-static.storage.googleapis.com/050548bae767435282242b1c404c6348/0000.png'),
('Basico', 5, '(Enem 2023)', 'No man is an island, Entire of itself; Every man is a piece of the continent, A part of the main. [...] Any man s death diminishes me, Because I am involved in mankind.', 'Nesse poema, a expressão No man is an island ressalta o(a):', NULL),
('Basico', 6, '(Enem 2022)', 'As my official bio reads, I was made in Cuba, assembled in Spain, and imported to the United States – meaning my mother, seven months pregnant, and the rest of my family arrived as exiles from Cuba to Madrid, where I was born. Less than two months later, we emigrated once more and settled in New York City, then eventually in Miami, where I was raised and educated. Although technically we lived in the United States, the Cuban community was culturally insular in Miami during the 1970s, bonded together by the trauma of exile. What s more, it seemed that practically everyone was Cuban my teachers, my classmates, the mechanic, the bus driver. I didn t grow up feeling different or treated as a minority. The few kids who got picked on in my grade school were the ones with freckles and funny last names like Dawson and O Neil.', 'Ao relatar suas vivências, o autor destaca o(a):', NULL),
('Basico', 7, '(Enem 2022)', 'Two hundred years ago, Jane Austen lived in a world where single men boasted vast estates; single ladies were expected to speak several languages, sing and play the piano. In both cases, it was, of course, advantageous if you looked good too. So, how much has – or hasn t – changed? Dating apps opaquely outline the demands of today s relationship market; users ruminate long and hard over their choice of pictures and what they write in their biographies to hook in potential lovers, and that s just your own profile. What do you look for in a future partner s profile – potential signifiers of a popular personality, a good job, a nice car? These apps are a poignant reminder of the often classist attitudes we still adopt, as well as the financial and aesthetic expectations we demand from potential partners.', 'O texto aborda relações interpessoais com o objetivo de:', NULL),
('Basico', 8, '(Enem 2020)', NULL, 'No cartum, o estudante faz uma pergunta usando turn this thing on por:', 'https://storage.googleapis.com/novo-blog-wordpress/2024/05/e652e2f6-unnamed-30.png'),
('Basico', 9, '(Enem 2022)', 'A Teen s View of Social Media Instagram is made up of all photos and videos. There is the home page that showcases the posts from people you follow, an explore tab which offers posts from accounts all over the world, and your own page, with a notification tab to show who likes and comments on your posts. It has some downsides though. It is known to make many people feel insecure or down about themselves because the platform showcases the highlights of everyone s lives, while rarely showing the negatives. This can make one feel like their life is not going as well as others, contributing to the growing rates of anxiety or depression in many teens today. There is an underlying desire for acceptance through the number of likes or followers one has.', 'O termo downsides introduz a ideia de que o Instagram é responsável por:', NULL),
('Basico', 10, '(Enem 2021)', 'Becomin Back in the ancestral homeland of Michelle Obama, black women were rarely granted the honorific Miss or Mrs., but were addressed by their first name, or simply as gal or auntie or worse. This so openly demeaned them that many black women, long after they had left the South, refused to answer if called by their first name. A mother and father in 1970s Texas named their newborn Miss so that white people would have no choice but to address their daughter by that title. Black women were meant for the field or the kitchen, or for use as they saw fit. They were, by definition, not ladies. The very idea of a black woman as first lady of the land, well, that would have been unthinkable.', 'A crítica do livro de memórias de Michelle Obama, ex-primeira-dama dos EUA, aborda a história das relações humanas na cidade natal da autora. Nesse contexto, o uso do vocábulo unthinkable ressalta que:', NULL),
('Basico', 11, '(Enem 2020)', 'A Minor Bird I have wished a bird would fly away, And not sing by my house all day; Have clapped my hands at him from the door When it seemed as if I could bear no more. The fault must partly have been in me. The bird was not to blame for his key. And of course there must be something wrong In wanting to silence any song.', 'No poema de Robert Frost, as palavras fault e blame revelam por parte do eu lírico uma:', NULL),
('Basico', 12, '(Enem 2011)', NULL, 'Na fase escolar, é prática comum que os professores passem atividades extraclasse e marquem uma data para que as mesmas sejam entregues para correção. No caso da cena da charge, a professora ouve uma estudante apresentando argumentos para:', 'https://d2q576s0wzfxtl.cloudfront.net/2017/08/08150628/questao92.enem2011.png'),
('Basico', 13, '(Enem 2012)', 'Quotes Of The Day Friday, Sep. 02, 2011 There probably was a shortage of notaries in my town. I m the kind of guy who never reads the letter X or anything, even though the man gave it to me three times, No, said the other, We have to find a way to show you you re wrong, but you re also right, we can put this question in a folder. It s already obvious that he never read that text, and it s hard to believe he was also wrong about the text.', 'Em relação à charge, a parte em que a fala We have to find a way to show you you re wrong revela um tipo de discurso:', NULL),
('Basico', 14, '(Enem 2013)', 'The best teachers are those who show you where to look, but don t tell you what to see.', 'A frase apresentada expressa a ideia de que os melhores professores:', NULL),
('Basico', 15, '(Enem 2014)', 'The advertisement is a powerful tool for companies to promote their products. It is a way to communicate with the public and make them aware of the products and services that the company offers. The advertisement can be in the form of a poster, a commercial on TV, a radio jingle, or a banner on a website. The advertisement can be used to inform the public about new products, services, or promotions. It can also be used to persuade the public to buy a product or service. The advertisement can be used to create brand awareness and build brand loyalty. The advertisement can be used to reach a large audience and increase sales. The advertisement can be used to create a positive image of the company and its products. The advertisement can be used to create a competitive advantage for the company.', 'O texto tem como objetivo:', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_ec534fc94ba9ef0ebf3ad516d3ee6884_101825.jpg.jpeg');

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES 
(1, 'Basico', 'a) necessidade de acessar informações confiáveis.', FALSE),
(1, 'Basico', 'b) dificuldade de conciliar diferentes anseios.', TRUE),
(1, 'Basico', 'c) desejo de dominar novas tecnologias.', FALSE),
(1, 'Basico', 'd) desafio de permanecer imparcial.', FALSE),
(1, 'Basico', 'e) vontade de ler notícias positivas.', FALSE),
(2, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(2, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(2, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(2, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(2, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(3, 'Basico', 'a) anunciar mercadorias em promoção.', TRUE),
(3, 'Basico', 'b) pedir para uma pessoa se retirar.', FALSE),
(3, 'Basico', 'c) comprar produtos fora de moda.', FALSE),
(3, 'Basico', 'd) indicar recessão na economia.', FALSE),
(3, 'Basico', 'e) chamar alguém em voz alta.', FALSE),
(4, 'Basico', 'a) revolta com a falta de sorte.', FALSE),
(4, 'Basico', 'b) receio pelo futuro do casamento.', FALSE),
(4, 'Basico', 'c) gosto pela prática da leitura.', TRUE),
(4, 'Basico', 'd) entusiasmo com os livros de terror.', FALSE),
(4, 'Basico', 'e) rejeição ao novo tipo de residência.', FALSE),
(5, 'Basico', 'a) medo da morte.', FALSE),
(5, 'Basico', 'b) ideia de conexão.', TRUE),
(5, 'Basico', 'c) conceito de solidão.', FALSE),
(5, 'Basico', 'd) risco de devastação.', FALSE),
(5, 'Basico', 'e) necessidade de empatia.', FALSE),
(6, 'Basico', 'a) mostrar que animais de estimação ajudam na cura de doenças como alergias e asma.', FALSE),
(6, 'Basico', 'b) esclarecer sobre o modo como os idosos devem se relacionar com animais de estimação.', FALSE),
(6, 'Basico', 'c) fornecer dados sobre os impactos de animais de estimação nas relações amorosas.', FALSE),
(6, 'Basico', 'd) explicar como o contato com animais de estimação pode prevenir ataques cardíacos.', FALSE),
(6, 'Basico', 'e) convencer sobre os benefícios da adoção de animais de estimação para a saúde.', TRUE),
(7, 'Basico', 'a) problematizar o papel de gênero em casamentos modernos.', FALSE),
(7, 'Basico', 'b) apontar a relevância da educação formal na escolha de parceiros.', FALSE),
(7, 'Basico', 'c) comparar a expectativa de parceiros amorosos em épocas distintas.', TRUE),
(7, 'Basico', 'd) discutir o uso de aplicativos para proporcionar encontros românticos.', FALSE),
(7, 'Basico', 'e) valorizar a importância da aparência física na seleção de pretendentes.', FALSE),
(8, 'Basico', 'a) suspeitar que o colega está com seu material por engano.', FALSE),
(8, 'Basico', 'b) duvidar que o colega possa se tornar um bom aluno.', FALSE),
(8, 'Basico', 'c) desconfiar que o livro levado é de outra matéria.', FALSE),
(8, 'Basico', 'd) entender como desligada a postura do colega.', FALSE),
(8, 'Basico', 'e) desconhecer como usar um livro impresso.', TRUE),
(9, 'Basico', 'a) oferecer recursos de fotografia.', FALSE),
(9, 'Basico', 'b) divulgar problemas dos usuários.', FALSE),
(9, 'Basico', 'c) estimular aceitação dos seguidores.', FALSE),
(9, 'Basico', 'd) provocar ansiedade nos adolescentes.', TRUE),
(9, 'Basico', 'e) aproximar pessoas ao redor do mundo.', FALSE),
(10, 'Basico', 'a) a ascensão social era improvável.', TRUE),
(10, 'Basico', 'b) a mudança de nome era impensável.', FALSE),
(10, 'Basico', 'c) a origem do indivíduo era irrelevante.', FALSE),
(10, 'Basico', 'd) o trabalho feminino era inimaginável.', FALSE),
(10, 'Basico', 'e) o comportamento parental era irresponsável.', FALSE),
(11, 'Basico', 'a) culpa por não poder cuidar do pássaro.', FALSE),
(11, 'Basico', 'b) atitude errada por querer matar o pássaro.', FALSE),
(11, 'Basico', 'c) necessidade de entender o silêncio do pássaro.', FALSE),
(11, 'Basico', 'd) sensibilização com relação à natureza do pássaro.', TRUE),
(11, 'Basico', 'e) irritação quanto à persistência do canto do pássaro.', FALSE),
(12, 'Basico', 'a) discutir sobre o conteúdo do seu trabalho já entregue.', FALSE),
(12, 'Basico', 'b) elogiar o tema proposto para o relatório solicitado.', FALSE),
(12, 'Basico', 'c) sugerir temas para novas pesquisas e relatórios.', FALSE),
(12, 'Basico', 'd) reclamar do curto prazo para entrega do trabalho.', FALSE),
(12, 'Basico', 'e) convencer de que fez o relatório solicitado.', TRUE),
(13, 'Basico', 'a) enfatizar a discriminação contra os jovens britânicos e suas famílias.', FALSE),
(13, 'Basico', 'b) criticar as ações agressivas demonstradas nos tumultos pelos jovens.', FALSE),
(13, 'Basico', 'c) estabelecer relação entre a falta de limites dos jovens e o excesso de amor.', FALSE),
(13, 'Basico', 'd) reforçar a ideia de que os jovens precisam de amor, mas também de firmeza.', TRUE),
(13, 'Basico', 'e) escrever o tipo de amor que gera problemas às famílias de jovens britânicos.', FALSE),
(14, 'Basico', 'a) temem quem as amedronta.', FALSE),
(14, 'Basico', 'b) aprendem com o que vivem.', TRUE),
(14, 'Basico', 'c) amam aqueles que as aceitam.', FALSE),
(14, 'Basico', 'd) são gentis quando respeitadas.', FALSE),
(14, 'Basico', 'e) ridicularizam quem as intimida.', FALSE),
(15, 'Basico', 'a) conscientizar sobre a necessidade de otimização do consumo.', TRUE),
(15, 'Basico', 'b) divulgar espaços publicitários de grande visibilidade.', FALSE),
(15, 'Basico', 'c) sensibilizar para a conservação do patrimônio público.', FALSE),
(15, 'Basico', 'd) apresentar uma forma mais econômica de fazer publicidade.', FALSE),
(15, 'Basico', 'e) denunciar possíveis danos decorrentes de atos de vandalismo.', FALSE);

-- Nível Intermediário
INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Intermediario', 1, '(Enem PPL 2014)', NULL, 'Implementar políticas adequadas de alimentação e nutrição é uma meta prioritária em vários países do mundo. A partir da campanha If you can t read it, why eat it?, os leitores são alertados para o perigo de:', 'https://pt-static.z-dn.net/files/dcc/225cbb6ae4390ccd53439b5c52105b2b.png'),
('Intermediario', 2, '(Enem 2014)', 'Tennessee Mountain Properties: Description- Own a renovated house for less than $290 per month!!!!!!!! New windows, siding, flooring (laminate throughout and tile in entry way and bathroom), kitchen cabinets, counter top, back door, fresh paint and laundry on main floor. Heat bills are very low due to a good solid house and an energy efficient furnace. Disponível em: www.freerealestaeads.net. Acesso em: 30 nov. 2011 (adaptado).', 'Em jornais, há diversos anúncios que servem aos leitores. O conteúdo do anúncio veiculado por este texto interessará a alguém que esteja procurando:', NULL),
('Intermediario', 3, '(Brasil Escola)', NULL, 'Qual das alternativas apresenta apenas advérbios de tempo?', NULL),
('Intermediario', 4, '(UNIP)', NULL, 'It s ________ honor to meet ________ young lady from Sweden.', NULL),
('Intermediario', 5, '(Enem PPL 2013)', NULL, 'Tirinhas são construídas a partir de contextos sociais e podem promover reflexões diversas. Essa tirinha provoca no leitor uma reflexão acerca da:', 'https://media.brainly.com.br/image/rs:fill/w:1920/q:75/plain/https://pt-static.z-dn.net/files/dc9/bfec51a193c0c9c0e130c59360ba45ab.png'),
('Intermediario', 6, '(Enem PPL 2011)', NULL, 'Ao estabelecer uma relação entre a Matemática e o blues a partir da opinião pessoal de um dos rapazes, a charge sugere que:', 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS8-Y2R6QlDkiyev8W2kFRQSqSQPPUuOCgzNz5lcnB_HTofWdtk'),
('Intermediario', 7, '(Enem 2014)', 'The Road Not Taken (by Robert Frost): Two roads diverged in a wood, and I — I took the one less traveled by, And that has made all the difference. Disponível em: www.poetryfoundation.org. Acesso em: 29 nov. 2011 (fragmento).', 'Estes são os versos finais do famoso poema The Road Not Taken, do poeta americano Robert Frost. Levando-se em consideração que a vida é comumente metaforizada como uma viagem, esses versos indicam que o autor:', NULL),
('Intermediario', 8, '(Enem PPL 2010)', 'Crystal Ball: Come see your life in my crystal glass — Twenty-five cents is all you pay Let me look into your past — Here s what you had for lunch today: Tuna salad and mashed potatoes, Collard greens pea soup and apple juice, Chocolate milk and lemon mousse. You admit I ve got told it all? Well, I know it, I confess, Not by looking, in my ball, But just by looking at your dress. SILVERSTEIN, S. Falling up. New York: Harper Collins Publishers, 1996.', 'A curiosidade a respeito do futuro pode exercer um fascínio peculiar sobre algumas pessoas, a ponto de colocá-las em situações inusitadas. Na letra da música Crystal Ball, essa situação fica evidente quando é revelado à pessoa que ela:', NULL),
('Intermediario', 9, '(Unesp)', NULL, 'Indique a alternativa que expressa o mesmo significado de: When children watch TV, they encounter a wide range of places, people, and information.', NULL),
('Intermediario', 10, '(Enem, 2020)', 'Finally, Aisha finished with her customer and asked what colour Ifemelu wanted for her hair attachments. “Colour four.” “Not good colour,” Aisha said promptly. “That s what I use.” “It look dirty. You don t want colour one?” “Colour one it too black. It looks fake,” Ifemelu said, loosening her headwrap. “Sometimes I use colour two, but colour four is closest to my natural colour.” […] She touched Ifemelu s hair. “Why you don t have relaxer?” “I like my hair the way God made it.” “But how do you comb it? Hard to comb,” Aisha said. Ifemelu had brought her own comb. She gently combed her hair, dense, soft and tightly coiled, until it framed her head like a halo. “It s not hard to comb if you moisturize it properly,” she said, slipping into the coaxing tone of the proselytizer that she used whenever she was trying to convince other black women about the merits of wearing their hair natural. Aisha snorted; she clearly could not understand why anybody would choose to suffer through combing natural hair, plucked a little attachment from the pile on the table ad began deftly to twist. ADICHIE, C. Americanah: A novel. New York: Anchor Books, 2013.', 'A passagem do romance da escritora nigeriana traz um diálogo entre duas mulheres negras: a cabeleireira, Aisha, e a cliente, Ifemelu. O posicionamento da cliente é sustentado por argumentos que:', NULL),
('Intermediario', 11, '(Enem, 2020)', NULL, 'Os recursos usados nesse pôster de divulgação de uma campanha levam o leitor a refletir sobre a necessidade de:', 'https://www.notamaxima.com.br/upl/uploads/enem_2020_1_dia_indagacao_02.jpg'),
('Intermediario', 12, '(Enem em inglês, 2018)', 'Don t write in English, they said, English is not your mother tongue… …The language I speak Becomes mine, its distortions, its queerness All mine, mine alone, it is half English, half Indian, funny perhaps, but it is honest, It is as human as I am human… …It voices my joys, my longings my Hopes… (Kamala Das, 1965:10) GARGESH, R. South Asian Englishes. In: KACHRU, B.B.; KACHRU, Y.; NELSON, C.L. (Eds.). The Handbook of World English. Singapore: Blackwell, 2006', 'A poetisa Kamala Das, como muitos escritores indianos, escreve suas obras em inglês, apesar de essa não ser sua primeira língua. Nesses versos, ela:', NULL),
('Intermediario', 13, '(Enem/2018)', 'Is it your opinion, Winston, that the past has real existence?/ [...] O\Brien smiled faintly. \I will put it more precisely. Does the past exist concretely, in space? Is there somewhere or other a place, a world of solid objects, where the past is still happening?\ \No.\ \Then where does the past exist, if at all? \In records. It is written down.\ \In records. And — —?\ \In the mind. In human memories.\ \In memory. Very well, then. We, the Party, control all records, and we control all memories. Then we control the past, do we not?\ ORWELL. G, Nineteen Eighty-Four. New York: Signet Classics, 1977', 'O romance 1984 descreve os perigos de um Estado totalitário. A ideia evidenciada nessa passagem é que o controle do Estado se dá por meio do(a):', NULL),
('Intermediario', 14, '(Enem 2012)', 'DONAR. Disponível em: http://politicalgraffiti.wordpress.com. Acesso em: 17 ago. 2011.', 'Cartuns são produzidos com o intuito de satirizar comportamentos humanos e assim oportunizam a reflexão sobre nossos próprios comportamentos e atitudes. Nesse cartum, a linguagem utilizada pelos personagens em uma conversa em inglês evidencia a:', 'https://rachacuca.com.br/media/vestibulator/attachment/569-cartum-donar.png'),
('Intermediario', 15, '(Enem/2018)', 'Lava Mae: Creating Showers on Wheels for the Homeless- San Francisco, according to recent city numbers, has 4,300 people living on the streets. Among the many problems the homeless face is little or no access to showers. San Francisco only has about 16 to 20 shower stalls to accommodate them. But Doniece Sandoval has made it her mission to change that. The 51-year-old former marketing executive started Lava Mae, a sort of showers on wheels, a new project that aims to turn decommissioned city buses into shower stations for the homeless. Each bus will have two shower stations and Sandoval expects that they\ll be able to provide 2,000 showers a week. ANDREANO, C. Dísponível em: abcnews.go.com. Acesso: 26 jun. 2015 (adaptado).', 'A relação dos vocábulos shower, bus e homeless, no texto, refere-se a:', NULL);

INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Intermediario', 'a) acessarem informações equivocadas sobre a formulação química de alimentos empacotados.', FALSE),
(1, 'Intermediario', 'b) consumirem alimentos industrializados sem o interesse em conhecer a sua composição.', TRUE),
(1, 'Intermediario', 'c) desenvolverem problemas de saúde pela falta de conhecimento a respeito do teor dos alimentos.', FALSE),
(1, 'Intermediario', 'd) incentivarem crianças a ingerirem grande quantidade de alimentos processados e com conservantes.', FALSE),
(1, 'Intermediario', 'e) ignorarem o aumento constante da obesidade causada pela má alimentação na fase de desenvolvimento da crianças.', FALSE),
(2, 'Intermediario', 'a) emprego no setor imobiliário.', FALSE),
(2, 'Intermediario', 'b) imóvel residencial para compra.', TRUE),
(2, 'Intermediario', 'c) serviço de reparos em domicílio.', FALSE),
(2, 'Intermediario', 'd) pessoa para trabalho doméstico.', FALSE),
(2, 'Intermediario', 'e) curso de decorador de interiores.', FALSE),
(3, 'Intermediario', 'a) already, always, then, above.', FALSE),
(3, 'Intermediario', 'b) first, here, rarely, yet.', FALSE),
(3, 'Intermediario', 'c) below, before, never, hard.', FALSE),
(3, 'Intermediario', 'd) first, already, usually, yet.', FALSE),
(3, 'Intermediario', 'e) lately, still, next, finaly.', TRUE),
(4, 'Intermediario', 'a) a / an.', FALSE),
(4, 'Intermediario', 'b) an / an.', FALSE),
(4, 'Intermediario', 'c) a / a.', FALSE),
(4, 'Intermediario', 'd) an / a.', TRUE),
(5, 'Intermediario', 'a) divisão de espaço com os pais.', FALSE),
(5, 'Intermediario', 'b) perda da atenção dos pais.', FALSE),
(5, 'Intermediario', 'c) semelhança com os pais.', TRUE),
(5, 'Intermediario', 'd) ausência dos pais.', FALSE),
(5, 'Intermediario', 'e) submissão aos pais.', FALSE),
(6, 'Intermediario', 'a) o blues, com seu ritmo depressivo, alivia o sentimento causado pela Matemática.', TRUE),
(6, 'Intermediario', 'b) as canções iniciadas com a contagem de 1 a 4 fazem lembrar o blues.', FALSE),
(6, 'Intermediario', 'c) as canções devem se iniciar com a contagem de 1 a 4 para se tornarem tristes.', FALSE),
(6, 'Intermediario', 'd) o blues, assim como a Matemática, consegue despertar um sentimento inspirador.', FALSE),
(6, 'Intermediario', 'e) o sentimento despertado pela Matemática serve como motivação para o blues.', FALSE),
(7, 'Intermediario', 'a) festeja o fato de ter sido ousado na escolha que fez em sua vida.', TRUE),
(7, 'Intermediario', 'b) lamenta por ter sido um viajante que encontrou muitas bifurcações.', FALSE),
(7, 'Intermediario', 'c) viaja muito pouco e que essa escolha fez toda a diferença em sua vida.', FALSE),
(7, 'Intermediario', 'd) reconhece que as dificuldades em sua vida foram todas superadas.', FALSE),
(7, 'Intermediario', 'e) percorre várias estradas durante as diferentes fases de sua vida.', FALSE),
(8, 'Intermediario', 'a) recebeu uma boa notícia.', FALSE),
(8, 'Intermediario', 'b) ganhou um colar de pedras.', FALSE),
(8, 'Intermediario', 'c) se sujou durante o almoço.', TRUE),
(8, 'Intermediario', 'd) comprou vestidos novos.', FALSE),
(8, 'Intermediario', 'e) encontrou uma moeda.', FALSE),
(9, 'Intermediario', 'a) When children watch TV, a wide range of places, people, and information will be encounter.', FALSE),
(9, 'Intermediario', 'b) When children watch TV, a wide range of places, people, and information are encountered.', FALSE),
(9, 'Intermediario', 'c) When children watch TV, a wide range of places, people, and information is encountered.', TRUE),
(9, 'Intermediario', 'd) When TV was watched, a wide range of places, people, and information are encountered by children.', FALSE),
(9, 'Intermediario', 'e) A wide range of places, people, and information will be encountered when children watched TV.', FALSE),
(10, 'Intermediario', 'a) reforçam um padrão de beleza.', FALSE),
(10, 'Intermediario', 'b) retratam um conflito de gerações.', FALSE),
(10, 'Intermediario', 'c) revelam uma atitude de resistência.', TRUE),
(10, 'Intermediario', 'd) demonstram uma postura de imaturidade.', FALSE),
(10, 'Intermediario', 'e) evidenciam uma mudança de comportamento.', FALSE),
(11, 'Intermediario', 'a) criticar o tipo de tratamento dado à mulher.', TRUE),
(11, 'Intermediario', 'b) rever o desempenho da mulher no trabalho.', FALSE),
(11, 'Intermediario', 'c) questionar a sobrecarga de atribuições da mulher.', FALSE),
(11, 'Intermediario', 'd) analisar as pesquisas acerca dos direitos da mulher.', FALSE),
(11, 'Intermediario', 'e) censurar a mulher pelo uso de determinadas palavras.', FALSE),
(12, 'Intermediario', 'a) usa a língua inglesa como efeito humorístico.', FALSE),
(12, 'Intermediario', 'b) recorre a vozes de vários escritores ingleses.', FALSE),
(12, 'Intermediario', 'c) adverte sobre o uso distorcido da língua inglesa.', FALSE),
(12, 'Intermediario', 'd) demonstra consciência de sua identidade linguística.', TRUE),
(12, 'Intermediario', 'e) reconhece a incompreensão na sua maneira de falar inglês.', FALSE),
(13, 'Intermediario', 'a) boicote a ideais libertários.', FALSE),
(13, 'Intermediario', 'b) veto ao culto das tradições.', FALSE),
(13, 'Intermediario', 'c) poder sobre memórias e registros.', TRUE),
(13, 'Intermediario', 'd) censura a produções orais e escritas.', FALSE),
(13, 'Intermediario', 'e) manipulação de pensamentos individuais.', FALSE),
(14, 'Intermediario', 'a) predominância do uso da linguagem informal sobre a língua padrão.', FALSE),
(14, 'Intermediario', 'b) dificuldade de reconhecer a existência de diferentes usos da linguagem.', TRUE),
(14, 'Intermediario', 'c) aceitação dos regionalismos utilizados por pessoas de diferentes lugares.', FALSE),
(14, 'Intermediario', 'd) necessidade de estudo da língua inglesa por parte dos personagens.', FALSE),
(14, 'Intermediario', 'e) facilidade de compreensão entre falantes com sotaques distintos.', FALSE),
(15, 'Intermediario', 'a) empregar moradores de rua em lava a jatos para ônibus.', FALSE),
(15, 'Intermediario', 'b) comissionar sem-teto para dirigir os ônibus da cidade.', FALSE),
(15, 'Intermediario', 'c) exigir das autoridades que os ônibus municipais tenham banheiros.', FALSE),
(15, 'Intermediario', 'd) abrigar dois mil moradores de rua em ônibus que foram adaptados.', FALSE),
(15, 'Intermediario', 'e) criar acesso a banhos gratuitos para moradores de rua.', TRUE);

-- Nível Avançado
INSERT INTO simulados (nivel, numero_pergunta, titulo, texto_pergunta, pergunta_texto, url)
VALUES
('Avancado', 1, '(IBFC INEP 2012)', NULL, 'The alternative that brings the sentences with the same meaning of “My cousin recovered from his health problems because he has completely changed his lifestyle” is', NULL),
('Avancado', 2, '(ADM&TEC 2024)', 'Netflix is trying to prove to the world that it is all grown up:
Netflix is trying to persuade Wall Street that it is now all grown up. After squeezing out millions of additional subscribers via its password sharing crackdown and through the introduction of cheaper advertiser-supported plans, the streamer knows that its growth spurts are coming to an end — and now it wants investors to stop obsessing over those pesky membership numbers and instead focus on other metrics.
"In our early days, when we had little revenue or profit, membership growth was a strong indicator of our future potential. But now we are generating very substantial profit and free cash flow. We are also developing new revenue streams like advertising and our extra member feature, so memberships are just one component of our growth", Netflix told shareholders as it reported quarterly earnings.
To that end, Netflix said that it will no longer report quarterly subscriber numbers, starting in 2025. Alas, the metric that Wall Street has forever judged Netflix on the metric that prompted legacy media companies to burn endless piles of cash in their bids to compete with the streamer — will be retired. The decision to shut off transparency on the metric represents a significant turning point in the streaming revolution. For years, Netflix has prided itself on being extraordinarily transparent. Now it is aiming to hold its cards closer to its chest. And given that streaming giant is the trendsetter in the space, one could expect that other media companies will be inspired by the company s move and also opt to cease reporting such data.
To be fair, what Netflix is saying is not necessarily off base either. As the company shifts its business model away from subscriptions and toward advertising and other revenue streams, it makes sense to consider how much time users are spending on the service. The more content a user consumes on Netflix, the more likely they are to continue paying for the service, and the more money Netflix then makes from that single subscriber. "We are focused on revenue and operating margin as our primary financial metrics — and engagement (i.e. time spent) as our best proxy for customer satisfaction,” Netflix underscored in its letter to shareholders.
Regardless, less transparency in an already opaque industry is not ideal. The walled garden of streaming already lacks the same detailed viewership data that Nielsen collects on linear television broadcasters. Now, visibility into the streaming world will get even dimmer.
The announcement from Netflix managed to overshadow its otherwise stellar quarter. The company handily beat expectations and added a staggering 9.3 million subscribers, meaning it now boasts nearly 270 million in total. Netflix also beat analyst expectations on both earnings and revenue. However, it was not all good news. Netflix forecasted its subscriber growth to be lower in quarter two, chalking it up to “typical seasonality.” That led the stock to slide nearly 5% in after-hours trading.
Whether "typical seasonality” is solely to blame, or whether the streamer is simply starting to hit a ceiling, is hard to tell. Perhaps it is a mix of both. Whatever the cause, the stock sliding on the less-than-ideal outlook is a prime example of why Netflix wants Wall Street to stop focusing on its subscriber numbers. And, in one year s time, investors won t have a choice.
', 'Based on Text |, mark the statements below as True (T) or False (F). ( ) ( ) Netflix s steps might lead other streaming companies to crack on reporting quarterly subscriber numbers.
( ) Excluding engagement, being less transparent is the key for Netflix to maintain its customer satisfaction.
( ) Netflix wants investors to stop obsessing over membership numbers and instead focus on other metrics.
( ) Falling short of expectations, the streaming company added a staggering 9.3 million subscribers.', NULL),
('Avancado', 3, '(CONTEMAX 2024)', 'Lisa is discussing instructions from her supervisor with a colleague. Convert the direct speech into reported speech. and choose the correct sentence. Supervisor: "You must prepare the lesson plans for next week." Lisa reported : "_____________________________"', NULL, NULL),
('Avancado', 4, '(FUVEST 2023)', 'We have been given no shortage of digital tools that should, in theory, help us work better, with more focus and efficiency, and connect us more easily with our colleagues. Instead, email, instant messaging, remote-meeting apps, work-flow and project-management software can feel like buckets with holes in the bottom, maddeningly inadequate to the task of keeping us from drowning in work. It is clear that something in the great digital-workplace experiment has gone wrong. Or maybe it is more accurate to say that it is still too early to expect that we would have figured out how to make things go right. "We are working now with new technologies that only emerged in the "90s," says Cal Newport, a Georgetown computer-science professor. "The idea that we immediately figured out the best way to use them is ahistorical. Of course we have not gotten it right yet."', 'The expression sublinhada no trecho "The idea that we immediately figured out the best way to use them is ahistorical" pode ser substituída, sem prejuízo do sentido, por', NULL),
('Avancado', 5, '(FUNDATEC 2024)', 'In the image below we can see a boy talking to the “Google Home Mini”, which is an electronic device, and then with a tiger:', 'Which of the alternatives below correctly fills out the gaps in the dialogue, from top to bottom?', 'https://i.pinimg.com/originals/ea/16/9f/ea169f227323170a1f7f037b194d1b1c.jpg'),
('Avancado', 6, '(PUC - SP 2017)', NULL, 'O candidato não conseguiu colocar a foto no passaporte porque :', 'https://d23vy2bv3rsfba.cloudfront.net/questoes_imagens/0_5b85b68d2f8153e441e0c5fbfd6fbda0_294928.jpg.jpeg'),
('Avancado', 7, '(PUC - SP 2017)', NULL, 'O infográfico tem como objetivo principal:', 'https://qcon-assets-production.s3.amazonaws.com/images/provas/74936/222.png'),
('Avancado', 8, '(UERJ 2015)', NULL, 'And I should know. (panel 4) Modal verbs can be used to refer to a speaker s attitude. The modal should indicates that Calvin believes his knowledge of the bad quality of the TV show would be characterized as:', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQXsJ6OxMOJFS8PpGYE97jYZCmqepfwyBIjmxoL370qNFPKUM5a'),
('Avancado', 9, '(VUNESP - 2014)', 'The Institute for Supply Management s (ISM) manufacturing index rose to 53.2 from 51.3 in January. A reading above 50 indicates expansion. Separate data showed construction spending rose slightly in January, helped by residential construction. Manufacturing and construction are key to the US economy and there were fears that severe weather across many parts of the US may have hurt the sectors. Bradley Holcomb, chair of ISM s survey committee, said that while several manufacturers said severe weather was impacting their business, “other comments reflect optimism in terms of demand and growth in the near term”. Meanwhile, data released by the US Department of Commerce, showed that construction spending rose 0.1% in January, from December. Compared to the same month last year, construction spending was up 9.3%. However, the bad weather conditions impacted car sales in February with General Motors, Toyota and Ford all posting declines in their deliveries. But the drop in sales was less than expected and manufacturers were upbeat about the prospects in the coming months. “February auto sales emerged from a chill in the second half of the month, positioning the industry for a strong March,” said Bill Fay, general manager at Toyota, which saw a fall in deliveries of 4% during the month. General Motors sales fell 1%, compared to analysts forecast of a 6% drop. Chrysler and Nissan Motors beat the trend with sales increases of 11% and 16% respectively. Analysts said that overall car sales during the month had been helped by incentives and discounts offered by dealers to lure customers to showrooms in an attempt to cushion the impact of the severe weather conditions. However, as weather conditions improve, the discounts will reduce.', 'The third paragraph shows that', NULL),
('Avancado', 10, '(PUC Campinas - 2016)', 'Leia o texto para responder à questão. The colors of the rainbow so pretty in the sky Are also on the faces of people passing .. I... I see friends ..II.. hands Saying, "how do you do?" They are really saying, I love you.', 'The word that correctly fills the blank ..II.. is', NULL),
('Avancado', 11, '(Instituto Access - 2024)', NULL, 'Choose the correct option to complete the sentence: "Sadly, many people __________ serious illnesses due to lack of early detection."', NULL),
('Avancado', 12, '(Instituto Access - 2024)', 'On Friday, a major tech failure disrupted services worldwide and highlighted the vulnerability of interconnected technologies. Cybersecurity firm CrowdStrike apologized after an update to its antivirus software, which protects Microsoft Windows devices from attacks, caused a global outage. This led to thousands of flight cancellations and delays and affected banking, healthcare, and payment systems. Although the software bug has been fixed, experts warn that manually rebooting each affected computer will take significant time and effort. Microsoft estimated that 8.5 million computers globally were impacted by the glitch, making it the worst cyber event in history. The UK s National Cyber Security Centre and Germany s IT security agency have warned that scammers might exploit the situation. Despite the fix, it will take time to resolve all issues and clear backlogs. It is important to be prepared for such disruptions in the future and have resilient systems.', 'Read and mark the option which fills in the blanks accordingly.', NULL),
('Avancado', 13, '(Instituto Access - 2024)', NULL, 'Analise as sentenças e selecione a opção que apresenta a conjugação INCORRETA do tempo verbal perfeito.', NULL),
('Avancado', 14, '(VUNESP - 2013)', 'A transformer has a primary winding circuit with 200 turns and a secondary winding circuit with 10 turns. In an ideal, lossless, transformer model, the magnetic core permeability is infinite despite the voltages applied to the windings, the two windings are perfectly coupled and there are no internal resistance in the conductors. In such transformer, when a sinusoidal voltage is applied at the secondary winding with an amplitude of 5,0 [V] RMS, the RMS voltage in the primary winding terminals is equal to 100,0 [V].', 'Com relação a esse texto, assinale a alternativa correta.', NULL),
('Avancado', 15, '(VUNESP - 2023)', 'Leia o texto para responder a questão. Learning strategies are defined as “specific actions, behaviors, steps, or techniques—such as seeking out conversation partners, or giving one self-encouragement to tackle a difficult language task—used by students to enhance their own learning. When the learner consciously chooses strategies that suit his or her learning style and the L2 task at hand, these strategies become a useful toolkit for active, conscious, and purposeful self-regulation of learning. Learning strategies can be classified into six types; the compensatory strategies, for example, are those that help the learner make up for missing knowledge. A given strategy is neither good nor bad; it is neutral until the context of its use is thoroughly considered. What makes a strategy positive and helpful for a given learner? A strategy is useful if the following conditions are present: (a) the strategy relates to the L2 task at hand; (b) the strategy fits the particular student s learning style preferences to one degree or another; and (c) the student employs the strategy effectively and links it with other relevant strategies. Strategies that fulfill these conditions “make learning easier, faster, more enjoyable, more self-directed, more effective, and more transferable to new situations” (Oxford 1990, p. 8). Learning strategies can also enable students to become more independent and lifelong learners.', 'In a reading class, the text is about “World Cup host countries in the 21st century”. Aware of the fact that “a strategy is useful if it relates to the L2 task at hand”, the teacher coherently offers the following instruction to develop learners ability to scan texts in English:', NULL);


INSERT INTO alternativas (id_pergunta, nivel, texto_alternativa, correta)
VALUES
(1, 'Avancado', 'If my cousin did not have change his lifestyle completely, he would not recover from his health problems.', 'FALSE'),
(1, 'Avancado', 'If my cousin has not completely changed his lifestyle, he could not have recovered from his health problems.', 'FALSE'),
(1, 'Avancado', 'If my cousin has not completely changed his lifestyle, he would not have recovered from his health problems.', 'FALSE'),
(1, 'Avancado', 'If my cousin had not completely changed his lifestyle, he would not have recovered from his health problems.', 'TRUE'),
(1, 'Avancado', 'If my cousin had not completely changed his lifestyle, he would not recovered from his health problems.', 'FALSE'),
(2, 'Avancado', 'F. T. F. T.', 'FALSE'),
(2, 'Avancado', 'F. F. T. F.', 'TRUE'),
(2, 'Avancado', 'T. F. T. F.', 'FALSE'),
(2, 'Avancado', 'T. T. F. T.', 'FALSE'),
(3, 'Avancado', 'My supervisor said that we could prepare the lesson plans for next week.', 'FALSE'),
(3, 'Avancado', 'My supervisor said that we had to prepare the lesson plans for next week.', 'TRUE'),
(3, 'Avancado', 'My supervisor said that we must to prepare the lesson plans for next week.', 'FALSE'),
(3, 'Avancado', 'My supervisor said that we has to prepare the lesson plans for next week.', 'FALSE'),
(3, 'Avancado', 'My supervisor said that we might prepare the lesson plans for next week.', 'FALSE'),
(4, 'Avancado', 'disturbed', 'FALSE'),
(4, 'Avancado', 'constructed', 'FALSE'),
(4, 'Avancado', 'failed', 'FALSE'),
(4, 'Avancado', 'made', 'FALSE'),
(4, 'Avancado', 'understood', 'TRUE'),
(5, 'Avancado', 'to – no preposition – towards – to', 'FALSE'),
(5, 'Avancado', 'to – on – to – of', 'TRUE'),
(5, 'Avancado', 'no preposition – to – with – of', 'FALSE'),
(5, 'Avancado', 'to – no preposition – with – of', 'FALSE'),
(5, 'Avancado', 'no preposition – onto – with – to', 'FALSE'),
(6, 'Avancado', 'Exceeded the number of attempts that the machine allowed.', 'FALSE'),
(6, 'Avancado', 'Possibly did not have their ethnic-racial characteristics recognized by the program.', 'TRUE'),
(6, 'Avancado', 'Did not observe the technical criteria necessary to complete the procedure.', 'FALSE'),
(6, 'Avancado', 'Ignored the need to go through the items listed in the security aspects before making the next attempt.', 'FALSE'),
(7, 'Avancado', 'Give examples of types of electronic bullying so that parents can protect themselves.', 'FALSE'),
(7, 'Avancado', 'Show the bullied adolescent that they are not alone.', 'FALSE'),
(7, 'Avancado', 'Draw the populatio s attention to the fact that bullying is a dangerous reality.', 'FALSE'),
(7, 'Avancado', 'Show the population that combating bullying depends on each person s individual action.', 'TRUE'),
(8, 'Avancado', 'Desirable.', 'TRUE'),
(8, 'Avancado', 'Probable.', 'FALSE'),
(8, 'Avancado', 'Surprising.', 'FALSE'),
(8, 'Avancado', 'Mandatory.', 'FALSE'),
(9, 'Avancado', 'Auto manufacturers were already expecting a drop in sales for February.', 'TRUE'),
(9, 'Avancado', 'GM, Ford, and Toyota expected to sell more cars in February because of the winter.', 'FALSE'),
(9, 'Avancado', 'Car sales are expected to drop in the months after February when the winter finishes.', 'FALSE'),
(9, 'Avancado', 'Chrysler sold more cars than Toyota in February, but Nissan sold more than them all.', 'FALSE'),
(9, 'Avancado', 'General Motors sold 6% fewer cars than Toyota in February.', 'FALSE'),
(10, 'Avancado', 'Waving.', 'FALSE'),
(10, 'Avancado', 'Shaking.', 'TRUE'),
(10, 'Avancado', 'Grabbing.', 'FALSE'),
(10, 'Avancado', 'Clapping.', 'FALSE'),
(10, 'Avancado', 'Raising.', 'FALSE'),
(11, 'Avancado', 'Die from.', 'TRUE'),
(11, 'Avancado', 'Come down with.', 'FALSE'),
(11, 'Avancado', 'Contract.', 'FALSE'),
(11, 'Avancado', 'Are diagnosed with.', 'FALSE'),
(12, 'Avancado', 'Restarted - blackout - installing - news - robbers.', 'FALSE'),
(12, 'Avancado', 'Disrupted - outage - rebooting - glitch - scammers.', 'TRUE'),
(12, 'Avancado', 'Installed - chaos - cleaning - fact - thieves.', 'FALSE'),
(12, 'Avancado', 'Disturbed - news - reinstalling - story - programmers.', 'FALSE'),
(12, 'Avancado', 'Destroyed - coup - sending - failure - criminals.', 'FALSE'),
(13, 'Avancado', 'They had not eaten before the plane landed.', 'FALSE'),
(13, 'Avancado', 'I will have finished my report by this time next week.', 'FALSE'),
(13, 'Avancado', 'If you had studied for your exam, you would have passed.', 'FALSE'),
(13, 'Avancado', 'He has written ten pages of the report.', 'FALSE'),
(13, 'Avancado', 'They have are married for nearly fifty years.', 'TRUE'),
(14, 'Avancado', 'In an ideal transformer, a non-sinusoidal voltage is applied to the secondary winding, with an amplitude of 5.0 RMS volts.', 'FALSE'),
(14, 'Avancado', 'In an ideal transformer, a sinusoidal voltage is applied to the primary winding, with an amplitude of 5.0 RMS volts.', 'FALSE'),
(14, 'Avancado', 'The ideal transformer, without losses, has infinite permeability, regardless of the intensity of the voltages applied to the windings, which are perfectly coupled without any internal resistance in their conductors.', 'TRUE'),
(14, 'Avancado', 'The ideal transformer, without losses, has infinite permissiveness, which depends on the intensity of the voltages applied to the windings, which are perfectly coupled without any internal resistance in their conductors.', 'FALSE'),
(14, 'Avancado', 'A transformer has a primary magnetic circuit with 200 turns and a secondary magnetic circuit with 10 turns.', 'FALSE'),
(15, 'Avancado', 'Focus on the text s key ideas and ignore other elaborate details.', 'FALSE'),
(15, 'Avancado', 'Carefully read the title and the first paragraph to anticipate the content of subsequent paragraphs.', 'FALSE'),
(15, 'Avancado', 'Activate your prior knowledge to create a mental image about text content.', 'FALSE'),
(15, 'Avancado', 'Compare the content of this text with texts you have read in Portuguese about the same theme.', 'FALSE'),
(15, 'Avancado', 'Identify the countries which have held World Cup Championships in the last 22 years.', 'TRUE');
